-- Create reference tables
CREATE TABLE Attack (
	Id INTEGER PRIMARY KEY,
	DerivationID INTEGER NOT NULL,
	Attack       TEXT    NOT NULL,
	StatUsed     TEXT    NOT NULL,
	AttackType   TEXT    NOT NULL,
	ItemRequired TEXT    NOT NULL,
	GutsUsed     INTEGER NOT NULL,
	Damage       INTEGER NOT NULL,
	GutsDown     INTEGER NOT NULL,
	Critical     INTEGER NOT NULL,
	Hit          INTEGER NOT NULL,
	MaxLevel     INTEGER NOT NULL,
	AttackRange  TEXT    NOT NULL,
	Growth       TEXT    NOT NULL,
	Effect       TEXT    NOT NULL,
	FOREIGN KEY(DerivationId) REFERENCES Derivation(Id)
);

CREATE TABLE Characteristic (
	Id INTEGER PRIMARY KEY,
	Characteristic TEXT NOT NULL,
	Description    TEXT NOT NULL
);

CREATE TABLE Derivation (
	Id INTEGER PRIMARY KEY,
	Derivation TEXT NOT NULL
);

CREATE TABLE Monster (
	Id INTEGER PRIMARY KEY,
	Monster       TEXT     NOT NULL,
	DerivationID  INTEGER  NOT NULL,
	RegionID      INTEGER  NOT NULL,
	Description   TEXT     NOT NULL,
	FOREIGN KEY(DerivationID) REFERENCES Derivation(ID)
	FOREIGN KEY(RegionID)     REFERENCES Region(ID)
);

CREATE TABLE Region (
	Id INTEGER PRIMARY KEY,
	Region TEXT NOT NULL
);

-- Populate reference tables with data
INSERT INTO Attack (DerivationId, Attack, StatUsed, AttackType, ItemRequired, GutsUsed, Damage, GutsDown, Critical, Hit, MaxLevel, AttackRange, Growth, Effect) VALUES
	(1, 'Ear Slap', 'Power', 'Beat', 'Jade Bit', 10, 10, 6, 1, 50, 10, 'Close', 'Hit +1', 'None'),
	(1, 'Lick', 'Intelligence', 'Water', 'Aqua Bit', 15, 8, 27, 4, 42, 6, 'Mid', 'Damage +1', 'None'),
	(1, 'Sneeze', 'Intelligence', 'Wind', 'Aurora Bit', 18, 13, 15, 13, 52, 7, 'Mid', 'Guts Down +2', 'None'),
	(1, 'Baku Advance', 'Power', 'Beat', 'Flare Bit', 23, 33, 23, 10, 35, 8, 'Long', 'Hit +1', 'None'),
	(1, 'Bowwow', 'Intelligence', 'Wind', 'Aurora Stone', 36, 28, 28, 8, 54, 6, 'Long', 'Guts Down +1, Damage +1', 'None'),
	(1, 'Jidanda', 'Power', 'Earth', 'Jade Stone', 29, 27, 26, 2, 42, 8, 'Mid', 'Hit +1', 'Dizzy'),
	(1, 'Roll Breath', 'Power', 'Beat', 'Flare Stone', 40, 60, 11, 9, 35, 10, 'Mid', 'Critical +1, Damage +1', 'None'),
	(1, 'Suck', 'Power', 'Wind', 'Aqua Stone', 50, 50, 36, 5, 45, 10, 'Close', 'Hit +1', 'None'),
	(1, 'Play', 'Intelligence', 'Wind', 'Aurora Orb', 40, 40, 25, 4, 40, 10, 'Close', 'Guts Down +1, Damage +1', 'Miss/Self-Destruct'),
	(1, 'Sleep', 'Intelligence', 'Heart', 'Jade Orb', 29, 0, 0, 0, 0, 0, 'Mid/Close', 'Unknown', 'Life Recovery'),
	(1, 'Sea of Tears', 'Intelligence', 'Water', 'Aqua Orb', 34, 40, 36, 1, 38, 8, 'Long', 'Guts Down +1, Damage +1', 'None'),
	(2, 'Beaban', 'Power', 'Beat', 'Jade Bit', 16, 12, 2, 4, 50, 10, 'Close', 'Hit +1', 'None'),
	(2, 'Horn Sweep', 'Power', 'Cut', 'Aurora Bit', 25, 10, 8, 22, 56, 10, 'Close', 'Critical +3', 'Dizzy'),
	(2, 'Back Fist', 'Power', 'Beat', 'Aqua Bit', 27, 24, 6, 7, 40, 6, 'Close', 'Damage +1', 'None'),
	(2, 'Super Charge', 'Power', 'Beat', 'Flare Bit', 36, 26, 12, 5, 46, 7, 'Mid', 'Damage +1', 'None'),
	(2, 'Vibrato', 'Intelligence', 'Wind', 'Aurora Stone', 30, 9, 30, 0, 50, 9, 'Mid/Long', 'Guts Down +1', 'Addled'),
	(2, 'Beattack', 'Power', 'Pound', 'Aqua Stone', 55, 36, 9, 33, 44, 10, 'Mid', 'Hit +1', 'None'),
	(2, 'Kachiage', 'Power', 'Earth', 'Jade Stone', 40, 40, 23, 5, 32, 10, 'Close', 'Damage +1', 'None'),
	(2, 'Galulubang', 'Power', 'Beat', 'Flare Stone', 46, 32, 7, 6, 52, 8, 'Close', 'Damage +1', 'None'),
	(2, 'Beakrocket', 'Power', 'Pound', 'Aurora Orb', 50, 50, 5, 5, 38, 10, 'Long', 'Damage +1', 'None'),
	(2, 'Beaklariat', 'Power', 'Beat', 'Flare Orb', 32, 24, 0, 7, 45, 10, 'Mid', 'Critical +2', 'None'),
	(3, 'Pinball', 'Power', 'Beat', 'Flare Bit', 10, 10, 5, 2, 52, 10, 'Mid', 'Critical +1, Hit +1', 'Wince'),
	(3, 'Rolling', 'Power', 'Beat', 'Jade Bit', 20, 28, 3, 3, 48, 8, 'Long', 'Damage +1', 'None'),
	(3, 'Swing', 'Power', 'Beat', 'Aqua Bit', 12, 16, 6, 3, 45, 4, 'Close', 'Damage +1', 'None'),
	(3, 'Go Go Go', 'Power', 'Beat', 'Aurora Bit', 15, 24, 4, 1, 37, 7, 'Mid', 'Damage +1', 'Dizzy'),
	(3, 'Big Spin', 'Power', 'None', 'Jade Stone', 33, 36, 33, 4, 59, 9, 'Close', 'Damage +1', 'None'),
	(3, 'Thundader', 'Power', 'None', 'Flare Stone', 30, 41, 11, 12, 42, 10, 'Mid', 'Hit +1', 'None'),
	(3, 'Koro Rocket', 'Power', 'Beat, Flame', 'Aurora Stone', 50, 55, 41, 10, 45, 10, 'Long', 'Damage +1, Guts Down +1', 'None'),
	(3, 'Blackhole', 'Intelligence', 'None', 'Aurora Orb', 50, 49, 0, 3, 40, 10, 'Mid', 'Hit +1', 'Drain'),
	(3, 'Meeting', 'Intelligence', 'Heart', 'Aurora Orb', 23, 0, 0, 0, 49, 5, 'Mid/Long', 'Guts -1', 'None'),
	(3, 'Balibo', 'Power', 'Beat', 'Flare Orb', 27, 29, 8, 8, 55, 10, 'Mid', 'Critical +3', 'None'),
	(4, 'Bow', 'Power', 'Beat', 'Jade Bit', 11, 7, 5, 2, 51, 5, 'Close', 'Guts Down +1', 'None'),
	(4, 'Head Throw', 'Power', 'Beat', 'Flare Bit', 21, 21, 15, 5, 32, 6, 'Long', 'Damage +1', 'None'),
	(4, 'Ab Boomerang', 'Intelligence', 'Cut', 'Aurora Bit', 16, 12, 3, 10, 48, 9, 'Mid', 'Critical +3', 'None'),
	(4, 'Bad Feeling', 'Intelligence', 'Heart', 'Aqua Bit', 20, 6, 24, 0, 46, 8, 'Mid/Long', 'Hit +1', 'Addled'),
	(4, 'Random Hit', 'Intelligence', 'Flame', 'Aurora Stone', 32, 34, 17, 22, 29, 9, 'Long', 'Damage +1', 'None'),
	(4, 'Three Piece', 'Power', 'Beat', 'Jade Stone', 44, 31, 12, 6, 50, 8, 'Long', 'Damage +1', 'None'),
	(4, 'Head Swing', 'Power', 'Beat', 'Aqua Stone', 30, 26, 11, 7, 40, 9, 'Mid', 'Hit +1', 'None'),
	(4, 'Bomb', 'Intelligence', 'Flame', 'Flare Stone', 38, 54, 20, 10, 24, 9, 'Mid', 'Damage +1, Critical +1', 'None'),
	(4, 'Self Bomb', 'Intelligence', 'Flame', 'Flare Orb', 60, 54, 20, 10, 48, 9, 'Close', 'Damage +1, Critical +1', 'Self-Destruct'),
	(4, 'Self Bomb', 'Intelligence', 'Wind', 'Aurora Orb', 27, 13, 25, 6, 42, 6, 'Mid', 'Damage +1', 'Dizzy'),
	(5, 'Dragon Tail', 'Power', 'Beat', 'Aqua Bit', 10, 11, 5, 3, 43, 10, 'Close', 'Hit +1', 'Dizzy'),
	(5, 'Dragon Bite', 'Power', 'Pound', 'Jade Bit', 15, 25, 6, 8, 36, 7, 'Close', 'Damage +1', 'None'),
	(5, 'Fire', 'Intelligence', 'Flame', 'Flare Bit', 21, 21, 18, 4, 50, 7, 'Long', 'Damage +1', 'None'),
	(5, 'Wing Storm', 'Intelligence', 'Wind', 'Aurora Bit', 18, 15, 8, 3, 55, 9, 'Mid', 'Hit +1', 'Dizzy'),
	(5, 'Mega Stomp', 'Power', 'Beat', 'Jade Stone', 30, 30, 26, 20, 45, 9, 'Long', 'Damage +1', 'Dizzy'),
	(5, 'Inferno', 'Intelligence', 'Flame', 'Flare Stone', 50, 50, 42, 15, 50, 8, 'Mid', 'Damage +1, Guts Down +1', 'None'),
	(5, 'Inferno', 'Power', 'Pound', 'Aqua Stone', 35, 62, 19, 12, 32, 8, 'Close', 'Hit +1', 'None'),
	(5, 'Wing Blade', 'Power', 'Cut', 'Aurora Stone', 40, 36, 12, 30, 55, 6, 'Long', 'Hit +1, Critical +3', 'None'),
	(5, 'Salamander', 'Power', 'Flame, Beat', 'Flare Orb', 50, 70, 40, 21, 35, 9, 'Long', 'Hit +1, Critical +3', 'None'),
	(5, 'Zero Gravity', 'Power', 'Earth', 'Jade Orb', 25, 33, 18, 4, 42, 10, 'Mid', 'Hit +1', 'None'),
	(6, 'Twin Legs', 'Power', 'Beat', 'Jade Bit', 10, 10, 5, 3, 40, 9, 'Close', 'Hit +1', 'None'),
	(6, 'Lightning', 'Power', 'Cut', 'Flare Bit', 18, 25, 5, 5, 32, 6, 'Mid', 'Damage +1', 'None'),
	(6, 'Thunder Wind', 'Power', 'Cut', 'Aurora Bit', 15, 12, 3, 3, 55, 10, 'Close', 'Hit +1', 'None'),
	(6, 'Avalanche', 'Power', 'Beat', 'Aqua Bit', 20, 15, 3, 4, 48, 5, 'Mid', 'Damage +1', 'None'),
	(6, 'Whirlwind', 'Power', 'Cut', 'Flare Stone', 32, 40, 4, 10, 35, 8, 'Mid', 'Hit +1', 'None'),
	(6, 'Gust', 'Intelligence', 'Cut, Wind', 'Aurora Stone', 25, 20, 6, 7, 50, 10, 'Long', 'Hit +1', 'Wince'),
	(6, 'Stray Bolts', 'Power', 'Pound', 'Jade Stone', 48, 41, 10, 9, 49, 10, 'Close', 'Hit +1', 'None'),
	(6, 'Stray Bolts', 'Power', 'Cut', 'Aqua Stone', 42, 37, 0, 36, 42, 5, 'Mid', 'Damage +1, Critical +2', 'None'),
	(6, 'Heaven Bolt', 'Power', 'Cut', 'Flare Orb', 50, 67, 10, 10, 32, 7, 'Long', 'Hit +1', 'None'),
	(6, 'Mine', 'Intelligence', 'Pound, Earth', 'Jade Orb', 38, 37, 16, 15, 38, 10, 'Long', 'Damage +1', 'None'),
	(7, 'Thuk Thuk', 'Power', 'Pound', 'Aqua Bit', 11, 7, 6, 2, 45, 8, 'Close', 'Varies', 'None'),
	(7, 'Thunderbolt', 'Intelligence', 'Thunder', 'Jade Bit', 16, 9, 16, 4, 48, 8, 'Mid', 'Varies', 'None'),
	(7, 'Ear Slap', 'Power', 'Beat', 'Aurora Bit', 18, 10, 4, 5, 54, 10, 'Mid', 'Varies', 'None'),
	(7, 'Gang Raid', 'Intelligence', 'Magic', 'Flare Bit', 24, 15, 10, 10, 38, 8, 'Long', 'Varies', 'None'),
	(7, 'Flame Breath', 'Intelligence', 'Flame', 'Flare Stone', 32, 34, 24, 16, 34, 7, 'Mid', 'Varies', 'None'),
	(7, 'Turn Stab', 'Power', 'Pound', 'Aurora Stone', 26, 20, 20, 4, 41, 7, 'Close', 'Varies', 'None'),
	(7, 'Javelin', 'Intelligence', 'Pound', 'Aqua Stone', 36, 38, 8, 12, 32, 9, 'Long', 'Varies', 'Wince'),
	(7, 'Skewer', 'Power', 'Pound', 'Jade Stone', 32, 34, 1, 26, 33, 10, 'Mid', 'Varies', 'None'),
	(7, 'Gang Bomb', 'Power', 'Flame', 'Flare Orb', 46, 43, 10, 10, 50, 8, 'Long', 'Varies', 'None'),
	(7, 'Gang Dance', 'Intelligence', 'Heart, Magic', 'Aurora Orb', 28, 17, 24, 26, 48, 8, 'Mid', 'Varies', 'Addled'),
	(7, 'Balloon Pop', 'Intelligence', 'Pound/Magic', 'Aqua Orb', 38, 18, 43, 8, 44, 9, 'Long', 'Varies', 'None'),
	(7, 'Crane', 'Power', 'Beat', 'Jade Orb', 42, 50, 36, 10, 39, 8, 'Long', 'Varies', 'Dizzy'),
	(8, 'Finger Flick', 'Power', 'Beat', 'Jade Bit', 10, 11, 4, 5, 51, 8, 'Close', 'Hit +1, Critical +1', 'None'),
	(8, 'Mega Kick', 'Power', 'Beat', 'Flare Bit', 20, 36, 3, 2, 35, 9, 'Close', 'Damage +1', 'None'),
	(8, 'Slap', 'Power', 'Beat', 'Aqua Bit', 16, 18, 8, 4, 45, 9, 'Close', 'Hit +1', 'Wince'),
	(8, 'Rocket Punch', 'Power', 'Beat', 'Aurora Bit', 24, 25, 5, 14, 52, 9, 'Long', 'Critical +3', 'None'),
	(8, 'Rock Slide', 'Power', 'Beat', 'Aqua Stone', 27, 36, 5, 2, 46, 9, 'Mid', 'Damage +1', 'None'),
	(8, 'Magnifist', 'Intelligence', 'Earth', 'Jade Stone', 24, 18, 11, 5, 55, 10, 'Long', 'Hit +1', 'Wince'),
	(8, 'Atomic Punch', 'Power', 'Beat', 'Flare Stone', 32, 52, 8, 10, 35, 7, 'Close', 'Damage +2', 'None'),
	(8, 'Tornado Punch', 'Power', 'Beat', 'Aurora Stone', 48, 56, 7, 9, 50, 6, 'Close', 'Damage +1, Hit +1', 'None'),
	(8, 'Olega Meteor', 'Power', 'Beat, Flame', 'Flare Orb', 50, 68, 18, 18, 40, 9, 'Close', 'Damage +1, Hit +1', 'None'),
	(8, 'Pitch', 'Power', 'Beat', 'Aurora Orb', 22, 17, 22, 25, 45, 9, 'Long', 'Hit +1', 'Addled'),
	(8, '1000 Tons', 'Power', 'Beat', 'Jade Orb', 20, 41, 7, 9, 28, 10, 'Mid', 'Damage +1', 'None'),
	(8, 'W Chop', 'Power', 'Beat', 'Aqua Orb', 35, 56, 11, 10, 35, 8, 'Close', 'Hit +1', 'None'),
	(9, 'Mini Punch', 'Power', 'Beat', 'Jade Bit', 10, 9, 6, 1, 48, 10, 'Close', 'Hit +1', 'None'),
	(9, 'Muhha', 'Intelligence', 'Wind', 'Aurora Bit', 20, 9, 24, 8, 53, 7, 'Long', 'Guts Down +2', 'Wince'),
	(9, 'Uncho', 'Power', 'Beat', 'Aqua Bit', 18, 21, 15, 5, 35, 7, 'Mid', 'Damage +1', 'None'),
	(9, 'Spin Bang', 'Power', 'Beat', 'Flare Bit', 25, 27, 10, 6, 42, 10, 'Close', 'Hit +1', 'None'),
	(9, 'Jidanda', 'Power', 'Beat', 'Aqua Stone', 32, 43, 23, 5, 32, 10, 'Close', 'Damage +1, every two levels +1 Critical', 'None'),
	(9, 'Bullet Head', 'Power', 'Beat', 'Flare Stone', 50, 40, 10, 13, 53, 10, 'Mid', 'Hit +1', 'None'),
	(9, 'Surprise', 'Intelligence', 'Heart', 'Aurora Stone', 30, 11, 45, 1, 50, 8, 'Mid', 'Guts Down +1, Effect +1', 'Wince'),
	(9, 'Spring Kick', 'Power', 'Beat', 'Jade Stone', 44, 40, 17, 34, 40, 10, 'Mid', 'Damage +1', 'None'),
	(9, 'Spin Upper', 'Power', 'Beat', 'Jade Orb', 36, 35, 15, 9, 45, 9, 'Long', 'Damage +1', 'None'),
	(9, 'Furry Fury', 'Intelligence', 'Heart', 'Aqua Orb', 20, 11, 46, 0, 35, 8, 'Mid', 'Hit +1', 'None'),
	(10, 'Drill Punch', 'Power', 'Beat', 'Jade Bit', 9, 10, 4, 1, 50, 8, 'Close', 'Hit +1, Critical +1', 'None'),
	(10, 'Beam', 'Intelligence', 'Thunder', 'Flare Bit', 12, 12, 5, 3, 56, 10, 'Long', 'Critical +3', 'None'),
	(10, 'Mega Blade', 'Power', 'Cut, Lightning', 'Aurora Bit', 15, 25, 6, 8, 34, 7, 'Close', 'Damage +1', 'None'),
	(10, 'Core Attack', 'Power', 'Beat', 'Aqua Bit', 18, 22, 5, 3, 43, 10, 'Mid', 'Hit +1', 'Dizzy'),
	(10, 'Remote Punch', 'Power', 'Beat', 'Jade Stone', 21, 27, 3, 4, 48, 10, 'Mid', 'Hit +1', 'None'),
	(10, 'Ion Cannon', 'Intelligence', 'Thunder', 'Flare Stone', 50, 54, 25, 17, 45, 9, 'Long', 'Guts Down +1, Damage +1', 'None'),
	(10, 'Giga Blade', 'Power', 'Cut, Thunder', 'Aurora Stone', 30, 44, 12, 15, 36, 10, 'Mid', 'Damage +1', 'None'),
	(10, 'Force Bomber', 'Intelligence', 'Flame', 'Aqua Stone', 28, 21, 21, 10, 57, 5, 'Long', 'Damage +1, Guts Down +1', 'None'),
	(10, 'Giga Shooter', 'Intelligence', 'Flame', 'Aqua Orb', 35, 14, 47, 5, 65, 8, 'Mid', 'Damage +1', 'None'),
	(10, 'Ray Field', 'Intelligence', 'Thunder', 'Jade Orb', 11, 0, 0, 0, 57, 3, 'Any', 'Guts Used -1', 'Defense Up'),
	(10, 'Mixing Echo', 'Intelligence', 'Wind', 'Aurora Orb', 20, 11, 33, 3, 47, 5, 'Mid', 'Damage +1, Guts Down +1', 'Addled'),
	(11, 'Jell Charge', 'Power', 'Beat', 'Aurora Bit', 11, 12, 5, 3, 50, 4, 'Close', 'Damage +1', 'None'),
	(11, 'Jell Hammer', 'Power', 'Beat', 'Jade Bit', 13, 24, 3, 8, 32, 6, 'Close', 'Damage +1', 'None'),
	(11, 'Jell Sweep', 'Power', 'Beat', 'Aqua Bit', 15, 15, 10, 3, 42, 10, 'Mid', 'Hit +1', 'Dizzy'),
	(11, 'Jell Cannon', 'Intelligence', 'Beat', 'Flare Bit', 24, 30, 16, 10, 40, 9, 'Long', 'Hit +1', 'None'),
	(11, 'Jell Wall', 'Power', 'Beat', 'Jade Stone', 26, 22, 10, 6, 61, 5, 'Close', 'Damage +1', 'Slow'),
	(11, 'Jell Swallow', 'Power', 'None', 'Aurora Stone', 25, 24, 24, 13, 35, 7, 'Close', 'Damage +1, Guts Down +1', 'None'),
	(11, 'Jell Hypnosis', 'Intelligence', 'Heart', 'Aqua Stone', 20, 8, 38, 0, 49, 6, 'Mid', 'Guts Down +2', 'Addled'),
	(11, 'Jell Hypnosis', 'Intelligence', 'Heart', 'Aqua Stone', 20, 8, 38, 0, 49, 6, 'Mid', 'Guts Down +2', 'Addled'),
	(11, 'Jell Combo', 'Power', 'Beat', 'Flare Stone', 36, 40, 7, 4, 54, 8, 'Mid', 'Hit +1, Critical +1', 'Addled'),
	(11, 'Jell Swing', 'Power', 'Beat', 'Jade Orb', 45, 47, 37, 20, 41, 7, 'Long', 'Critical +2, Hit +1', 'None'),
	(11, 'Jell Spa', 'Intelligence', 'Water', 'Aqua Orb', 40, 39, 0, 0, 39, 10, 'Mid', 'Hit +1', 'Drain'),
	(11, 'Jell Missle', 'Intelligence', 'Flame', 'Flare Orb', 52, 58, 40, 13, 39, 10, 'Mid', 'Damage +1, Guts Down +1', 'Self-Destruct'),
	(12, 'Upper Attack', 'Power', 'Cut', 'Jade Bit', 12, 10, 4, 2, 50, 8, 'Close', 'Hit +1, Critical +1', 'None'),
	(12, 'Death Size', 'Intelligence', 'Cut', 'Aurora Bit', 18, 13, 3, 12, 59, 10, 'Long', 'Critical +3', 'None'),
	(12, 'Slash', 'Power', 'Cut', 'Flare Bit', 15, 21, 3, 6, 32, 6, 'Mid', 'Damage +1', 'None'),
	(12, 'Death Claw', 'Intelligence', 'Magic', 'Aqua Bit', 24, 19, 0, 3, 39, 5, 'Mid', 'Damage +1', 'Drain'),
	(12, 'Air Slash', 'Power', 'Cut', 'Aurora Stone', 27, 24, 5, 20, 44, 10, 'Long', 'Hit +1', 'Wind'),
	(12, 'Chaos Slash', 'Power', 'Cut', 'Jade Stone', 50, 55, 16, 10, 37, 9, 'Close', 'Damage +1, Critical +1', 'None'),
	(12, 'Evil Spirit', 'Intelligence', 'Magic', 'Aqua Stone', 42, 29, 29, 1, 48, 10, 'Long', 'Guts Down +2', 'None'),
	(12, 'Dark Flame', 'Intelligence', 'Flame', 'Flare Stone', 50, 43, 11, 3, 51, 10, 'Mid', 'Hit +1', 'None'),
	(12, 'Death Gate', 'Intelligence', 'Magic', 'Jade Orb', 32, 38, 19, 3, 34, 8, 'Mid', 'Hit +1', 'None'),
	(12, 'Phantom Gate', 'Intelligence', 'Heart', 'Aqua Orb', 29, 13, 43, 0, 41, 9, 'Mid', 'Hit +1', 'Addled'),
	(13, 'Fin Slap', 'Power', 'Beat', 'Jade Bit', 11, 10, 5, 1, 45, 10, 'Close', 'Hit +1', 'Wince'),
	(13, 'Lesihorne', 'Intelligence', 'Wind', 'Aurora Bit', 20, 12, 18, 2, 54, 6, 'Mid', 'Guts Down +2', 'None'),
	(13, 'Tail Whip', 'Power', 'Beat', 'Aqua Bit', 23, 22, 7, 2, 50, 6, 'Close', 'Damage +1', 'None'),
	(13, 'Head Slap', 'Power', 'Beat', 'Flare Bit', 17, 25, 3, 1, 32, 7, 'Close', 'Damage +1', 'Dizzy'),
	(13, 'Tail Whip', 'Power', 'Beat', 'Aqua Bit', 23, 22, 7, 2, 50, 6, 'Close', 'Damage +1', 'None'),
	(13, 'Sole', 'Power', 'Beat', 'Flare Stone', 26, 26, 9, 6, 43, 10, 'Long', 'Hit +1', 'Wince'),
	(13, 'Water Gun', 'Intelligence', 'Water', 'Aqua Stone', 32, 33, 33, 5, 43, 7, 'Mid', 'Guts Down +1', 'None'),
	(13, 'Show Time', 'Power', 'Beat', 'Jade Stone', 47, 40, 50, 2, 40, 9, 'Close', 'Hit +1', 'Addled'),
	(13, 'Boomerang', 'Intelligence', 'Beat', 'Aurora Stone', 40, 31, 2, 50, 48, 10, 'Long', 'Hit +1', 'None'),
	(13, 'Submerge', 'Power', 'Beat', 'Jade Orb', 36, 35, 1, 2, 55, 8, 'Mid', 'Damage +1', 'None'),
	(13, 'Tsunami', 'Intelligence', 'Water', 'Aqua Orb', 50, 50, 13, 1, 50, 8, 'Long', 'Damage +1', 'None'),
	(14, 'Head', 'Power', 'Beat', 'Aurora Bit', 18, 24, 6, 4, 34, 7, 'Mid', 'Damage +1', 'Dizzy'),
	(14, 'Scratch', 'Power', 'Cut', 'Jade Bit', 15, 17, 2, 11, 42, 10, 'Close', 'Hit +1', 'None'),
	(14, 'Poko Punch', 'Power', 'Beat', 'Flare Bit', 10, 8, 5, 3, 53, 5, 'Close', 'Guts Down +1', 'None'),
	(14, 'Hawaiian', 'Intelligence', 'Heart', 'Aqua Bit', 21, 8, 38, 3, 46, 5, 'Mid/Long', 'Guts Down +1, Damage +1', 'None'),
	(14, 'Meow', 'Intelligence', 'Wind', 'Aqua Stone', 32, 29, 21, 16, 40, 9, 'Mid/Long', 'Damage +1', 'Wince'),
	(14, '10:10', 'Power', 'Cut', 'Jade Stone', 47, 50, 9, 50, 33, 8, 'Mid', 'Hit +1', 'None'),
	(14, 'Zap', 'Intelligence', 'Flare', 'Flare Stone', 50, 41, 19, 22, 48, 10, 'Long', 'Hit +1', 'None'),
	(14, 'Cat Fan', 'Power', 'Cut', 'Aurora Stone', 42, 36, 8, 9, 54, 9, 'Mid', 'Critical +1, Hit +1', 'None'),
	(14, 'Idol', 'Intelligence', 'Heart', 'Aqua Orb', 45, 0, 0, 0, 42, 7, 'Close', 'Nothing changes between levels', 'None'),
	(14, 'Cat Fool', 'Intelligence', 'Pound', 'Jade Orb', 37, 20, 15, 14, 70, 6, 'Close', 'Damage +1', 'None'),
	(15, 'Monta', 'Power', 'Beat', 'Flare Bit', 10, 8, 5, 14, 47, 10, 'Close', 'Hit +1', 'None'),
	(15, 'Koloron', 'Power', 'Beat', 'Jade Bit', 22, 20, 10, 9, 40, 9, 'Long', 'Hit +1', 'None'),
	(15, 'Mocchiri', 'Power', 'Beat', 'Aurora Bit', 20, 21, 16, 3, 33, 7, 'Mid', 'Damage +1', 'None'),
	(15, 'Tongue Lick', 'Intelligence', 'Beat', 'Aqua Bit', 15, 4, 24, 0, 48, 5, 'Mid', 'Hit +1, Guts Down +1', 'None'),
	(15, 'Gagaccha', 'Power', 'Beat', 'Jade Stone', 40, 29, 11, 13, 50, 10, 'Close', 'Critical +3', 'None'),
	(15, 'Mocchi Spray', 'Intelligence', 'Thunder', 'Flare Stone', 35, 23, 12, 9, 55, 7, 'Long', 'Damage +1', 'None'),
	(15, 'Mossama', 'Power', 'Beat', 'Aurora Stone', 36, 38, 18, 8, 35, 10, 'Mid', 'Damage +1', 'None'),
	(15, 'Monyuun', 'Intelligence', 'Wind', 'Aqua Stone', 32, 15, 36, 3, 45, 5, 'Mid', 'Damage +1', 'Wince'),
	(15, 'Mossaman', 'Power', 'Beat', 'Aurora Orb', 50, 41, 15, 12, 45, 7, 'Long', 'Damage +1, Guts Down +2', 'None'),
	(15, 'Mocchi Cannon', 'Intelligence', 'Thunder', 'Flare Orb', 50, 40, 12, 12, 48, 10, 'Long', 'Hit +1', 'None'),
	(15, 'Mochiiki', 'Power', 'Beat', 'Jade Orb', 24, 18, 7, 7, 51, 5, 'Close', 'Damage +1', 'None'),
	(16, 'Headbang', 'Power', 'Pound', 'Aurora Bit', 12, 17, 3, 2, 38, 8, 'Close', 'Hit +1', 'None'),
	(16, 'Dig', 'Power', 'Pound', 'Jade Bit', 20, 20, 5, 4, 52, 5, 'Long', 'Damage +1', 'None'),
	(16, 'Punch In', 'Power', 'Beat', 'Flare Bit', 10, 10, 3, 5, 50, 10, 'Close', 'Hit +1', 'None'),
	(16, 'Scratch', 'Intelligence', 'Wind', 'Aqua Bit', 18, 14, 16, 9, 45, 10, 'Mid', 'Hit +1', 'Wince'),
	(16, 'Break Spin', 'Power', 'Beat', 'Jade Stone', 37, 34, 17, 6, 50, 7, 'Mid', 'Damage +1, Guts Down +1', 'None'),
	(16, 'Head Spin', 'Power', 'Pound', 'Aurora Stone', 42, 55, 12, 12, 37, 9, 'Mid', 'Damage +1, Critical +1', 'None'),
	(16, 'Ground Beat', 'Intelligence', 'Earth', 'Flare Stone', 46, 45, 36, 3, 41, 9, 'Long', 'Damage +1, Critical +1', 'Dizzy'),
	(16, 'Sand Loop', 'Intelligence', 'Earth', 'Aqua Stone', 29, 15, 39, 4, 49, 10, 'Close', 'Hit +1', 'Wince'),
	(16, 'Dig Mosh', 'Power', 'Pound', 'Flare Orb', 47, 43, 9, 10, 55, 8, 'Long', 'Critical +1, Hit +1', 'None'),
	(16, 'The Earth', 'Power', 'Earth', 'Jade Orb', 50, 46, 46, 8, 42, 9, 'Mid', 'Critical +1, Damage +1', 'None'),
	(17, 'Tail Whip', 'Power', 'Beat', 'Jade Bit', 12, 10, 3, 2, 49, 9, 'Close', 'Critical +1, Hit +1', 'None'),
	(17, 'Dunk', 'Power', 'Beat', 'Flare Bit', 24, 30, 6, 10, 32, 8, 'Mid', 'Damage +1', 'None'),
	(17, 'Machine Gun', 'Intelligence', 'Beat', 'Aqua Bit', 20, 15, 8, 11, 45, 10, 'Long', 'Hit +1', 'Wince'),
	(17, 'Scratch', 'Power', 'Cut', 'Aurora Bit', 15, 17, 2, 11, 36, 9, 'Close', 'Hit +1', 'None'),
	(17, 'Air Raid', 'Intelligence', 'Beat', 'Aqua Stone', 42, 38, 11, 5, 44, 10, 'Long', 'Damage +1, Critical +1', 'None'),
	(17, 'Air Spin', 'Power', 'Cut', 'Aurora Stone', 50, 46, 22, 31, 34, 9, 'Long', 'Damage +1, Guts Down +1', 'None'),
	(17, 'Spike', 'Power', 'Beat', 'Flare Stone', 38, 24, 6, 24, 56, 10, 'Mid', 'Critical +3', 'None'),
	(17, 'Spin Crush', 'Power', 'Beat', 'Jade Stone', 48, 39, 15, 8, 47, 10, 'Close', 'Critical +3', 'None'),
	(17, 'Sound Wave', 'Intelligence', 'Wind', 'Aurora Orb', 24, 9, 29, 2, 47, 7, 'Mid', 'Guts Down +2', 'None'),
	(17, 'Full', 'Intelligence', 'None', 'Aqua Orb', 42, 0, 0, 0, 50, 6, 'Any', 'Nothing', 'Life Recovery'),
	(18, 'Needle Cutter', 'Power', 'Cut', 'Aurora Bit', 12, 12, 3, 2, 40, 6, 'Mid', 'Critical +3', 'None'),
	(18, 'Poison Shower', 'Intelligence', 'Magic', 'Aqua Bit', 24, 16, 20, 4, 42, 8, 'Mid', 'Guts Down +1', 'Stun'),
	(18, 'Heavy Punch', 'Power', 'Beat', 'Jade Bit', 15, 13, 0, 5, 50, 10, 'Close', 'Hit +1', 'None'),
	(18, 'Double Claw', 'Power', 'Pound', 'Flare Bit', 21, 25, 5, 12, 33, 6, 'Close', 'Damage +1', 'None'),
	(18, 'Energy Throw', 'Intelligence', 'Magic', 'Aqua Stone', 37, 23, 22, 8, 49, 8, 'Long', 'Damage +1', 'None'),
	(18, 'Hedge Cutter', 'Power', 'Pound', 'Aurora Stone', 25, 22, 5, 7, 44, 10, 'Mid', 'Hit +1', 'None'),
	(18, 'Screw Drive', 'Power', 'Pound', 'Flare Stone', 51, 51, 12, 10, 38, 9, 'Long', 'Hit +1', 'None'),
	(18, 'Bone Breaker', 'Power', 'Pound', 'Jade Stone', 33, 24, 4, 45, 41, 5, 'Close', 'Critical +1, Damage +1', 'None'),
	(18, 'Power Combo', 'Power', 'Cut', 'Aurora Orb', 41, 48, 20, 11, 30, 8, 'Mid', 'Critical +1, Damage +1', 'None'),
	(18, 'Energy Drain', 'Intelligence', 'Pound', 'Aqua Orb', 50, 33, 0, 2, 38, 8, 'Close', 'Damage +1', 'None'),
	(19, 'Miminta', 'Power', 'Beat', 'Jade Bit', 15, 10, 7, 3, 43, 10, 'Close', 'Hit +1', 'None'),
	(19, 'Octo Ink', 'Intelligence', 'Water', 'Aqua Ink', 21, 6, 28, 3, 40, 9, 'Mid', 'Hit +1', 'Wince'),
	(19, 'Octopipi', 'Intelligence', 'Magic', 'Flare Bit', 20, 12, 12, 3, 41, 6, 'Mid', 'Hit +1', 'Stun'),
	(19, 'Octo Beam', 'Intelligence', 'Flame', 'Aurora Bit', 28, 18, 7, 9, 48, 9, 'Long', 'Critical +3', 'None'),
	(19, 'Capoeria', 'Power', 'Beat', 'Flare Stone', 51, 41, 2, 4, 45, 10, 'Close', 'Hit +1', 'None'),
	(19, 'Sniper', 'Intelligence', 'Flame', 'Jade Stone', 50, 32, 15, 30, 40, 9, 'Long', 'Hit +1', 'None'),
	(19, 'Flappe', 'Intelligence', 'Ice', 'Aurora Stone', 45, 19, 24, 5, 55, 5, 'Close', 'Damage +1', 'Slow'),
	(19, 'Bubble Dance', 'Intelligence', 'Water', 'Aqua Stone', 36, 10, 37, 0, 50, 6, 'Mid', 'Guts Down +2', 'Slow'),
	(19, 'Sucker', 'Intelligence', 'Heart', 'Aqua Orb', 48, 15, 48, 4, 37, 7, 'Mid', 'Hit +1', 'Drain'),
	(19, 'Octo-Balloon', 'Power', 'Beat', 'Aurora Orb', 40, 28, 13, 13, 44, 6, 'Mid', 'Damage +1, Guts Down +1', 'Self-Destruct when hits'),
	(19, 'Octo Ball', 'Power', 'Beat', 'Flare Orb', 24, 31, 5, 6, 26, 8, 'Close', 'Damage +1', 'None'),
	(20, 'Fin Slap', 'Power', 'Beat', 'Aurora Bit', 12, 13, 3, 2, 43, 8, 'Close', 'Hit +1', 'None'),
	(20, 'Accel Spin', 'Power', 'Beat', 'Flare Bit', 16, 10, 9, 16, 48, 8, 'Close', 'Varies', 'None'),
	(20, 'Tail Slap', 'Power', 'Beat', 'Jade Bit', 18, 8, 13, 5, 50, 10, 'Mid', 'Varies', 'Dizzy'),
	(20, 'Ultrasonics', 'Intelligence', 'Heart', 'Aqua Bit', 18, 7, 26, 2, 47, 10, 'Long', 'Varies', 'None'),
	(20, 'Final Dance', 'Power', 'Thunder', 'Flare Stone', 36, 32, 18, 6, 46, 7, 'Close', 'Varies', 'None'),
	(20, 'Jet Fish', 'Power', 'Beat', 'Aqua Stone', 50, 46, 2, 28, 31, 9, 'Long', 'Varies', 'None'),
	(20, 'Squall', 'Intelligence', 'Wind, Heart', 'Jade Stone', 44, 33, 37, 3, 43, 8, 'Mid', 'Varies', 'None'),
	(20, 'Ice Beam', 'Intelligence', 'Heart', 'Aurora Stone', 36, 8, 42, 0, 48, 8, 'Mid/Long', 'Varies', 'Slow'),
	(20, 'Torrent', 'Intelligence', 'Heart, Water', 'Aqua Orb', 44, 9, 42, 10, 46, 8, 'Mid/Long', 'Varies', 'None'),
	(20, 'Un-Deux-Trois', 'Intelligence', 'Magic', 'Flare Orb', 27, 9, 20, 8, 46, 9, 'Long', 'Varies', 'None'),
	(20, 'Vortex', 'Intelligence', 'Water, Heart', 'Aurora Orb', 27, 9, 20, 8, 46, 9, 'Close', 'Varies', 'None'),
	(20, 'Earth Wave', 'Intelligence', 'Heart, Magic', 'Jade Orb', 38, 24, 6, 2, 41, 9, 'Mid', 'Varies', 'None'),
	(21, 'Knock', 'Power', 'Beat', 'Flare Bit', 15, 15, 2, 2, 37, 9, 'Mid', 'Hit +1', 'None'),
	(21, 'Boomerang', 'Power', 'Cut', 'Aurora Bit', 20, 11, 4, 32, 50, 7, 'Long', 'Critical +2', 'None'),
	(21, 'Magic Hand', 'Intelligence', 'Beat', 'Jade Bit', 12, 7, 5, 2, 52, 8, 'Close', 'Hit +1', 'None'),
	(21, 'Cracker', 'Intelligence', 'Heart', 'Aqua Bit', 24, 10, 29, 1, 40, 6, 'Long', 'Guts Down +2', 'Wince'),
	(21, 'Pitching', 'Power', 'Beat', 'Flare Stone', 30, 29, 9, 5, 35, 8, 'Long', 'Damage +1', 'None'),
	(21, 'Surprise', 'Intelligence', 'Heart', 'Aurora Stone', 36, 10, 41, 0, 47, 10, 'Close', 'Hit +1', 'Wince'),
	(21, 'Trumpet Rush', 'Intelligence', 'None', 'Jade Stone', 50, 43, 10, 1, 42, 10, 'Mid', 'Damage +1', 'None'),
	(21, 'Heavy Attack', 'Intelligence', 'Water', 'Aqua Stone', 42, 25, 5, 15, 55, 6, 'Mid', 'Damage +1', 'None'),
	(21, 'Blow Arrow', 'Intelligence', 'Pound', 'Jade Orb', 27, 18, 3, 50, 35, 8, 'Mid', 'Hit +1', 'Stun'),
	(21, 'Empty', 'Power', 'Beat', 'Aqua Orb', 48, 26, 10, 6, 60, 5, 'Close', 'Damage +1', 'Stun'),
	(22, 'Empty', 'Power', 'Beat', 'Jade Bit', 10, 8, 2, 3, 42, 10, 'Close', 'Hit +1', 'None'),
	(22, 'Wind Lance', 'Intelligence', 'Beat', 'Aurora Bit', 24, 21, 5, 12, 36, 6, 'Mid', 'Damage +1', 'None'),
	(22, 'Raycast', 'Intelligence', 'Magic', 'Aqua Bit', 13, 7, 4, 5, 48, 10, 'Close', 'Critical +2', 'None'),
	(22, 'Star Light', 'Intelligence', 'Magic', 'Flare Bit', 25, 14, 10, 6, 50, 5, 'Long', 'Damage +1', 'None'),
	(22, 'Fairy Dust', 'Intelligence', 'Magic', 'Jade Stone', 42, 22, 18, 1, 54, 4, 'Mid', 'Damage +1, Guts Down +2', 'None'),
	(22, 'Milky Way', 'Intelligence', 'Heart', 'Aurora Stone', 32, 16, 34, 5, 36, 6, 'Mid', 'Guts Down +1, Hit +1', 'Addled'),
	(22, 'Star Gather', 'Intelligence', 'Magic', 'Flare Stone', 50, 40, 10, 10, 40, 10, 'Long', 'Damage +1', 'None'),
	(22, 'Heal Ring', 'Intelligence', 'Magic', 'Aqua Stone', 48, 0, 0, 0, 45, 10, 'Long', 'Nothing, they stats stay the same throughout all levels', 'None'),
	(22, 'Silky Dance', 'Intelligence', 'Heart', 'Aurora Orb', 32, 6, 33, 0, 52, 5, 'Close', 'Damage +1', 'None'),
	(22, 'Heart Breaker', 'Intelligence', 'Beat', 'Flare Orb', 49, 34, 24, 5, 39, 10, 'Close', 'Hit +1', 'Wince'),
	(22, 'Fairy Kiss', 'Intelligence', 'Heart', 'Aqua Orb', 17, 0, 37, 0, 39, 9, 'Close', 'Hit +1', 'None'),
	(22, 'Element Guard', 'Intelligence', 'Magic', 'Jade Orb', 46, 0, 0, 0, 40, 9, 'Any', 'Hit +1', 'Despair'),
	(23, 'Stab', 'Power', 'Pound', 'Jade Bit', 10, 7, 2, 1, 48, 5, 'Close', 'Guts Down +1', 'None'),
	(23, 'Pollen', 'Intelligence', 'Magic', 'Aurora Bit', 25, 11, 21, 3, 42, 6, 'Mid', 'Hit +1, Guts Down +1', 'Wince'),
	(23, 'Slap', 'Power', 'Beat', 'Flare Bit', 15, 9, 2, 2, 51, 10, 'Close', 'Hit +1', 'Wince'),
	(23, 'Flower Dance', 'Intelligence', 'Heart', 'Aqua Bit', 20, 3, 28, 0, 58, 4, 'Mid', 'Guts Down +2', 'None'),
	(23, 'Flowercopter', 'Power', 'Beat', 'Aqua Stone', 42, 39, 6, 3, 38, 10, 'Long', 'Damage +1', 'None'),
	(23, 'Flower Storm', 'Intelligence', 'Wind', 'Aurora Stone', 33, 11, 19, 5, 54, 7, 'Mid', 'Hit +1, Guts Down +1', 'Dizzy'),
	(23, 'Seed Gatling', 'Intelligence', 'Beat', 'Flare Stone', 40, 26, 4, 18, 48, 9, 'Long', 'Critical +3', 'None'),
	(23, 'Root Uppercut', 'Power', 'Beat', 'Jade Stone', 45, 25, 1, 6, 58, 7, 'Mid', 'Damage +1', 'Dizzy'),
	(23, 'Drain', 'Intelligence', 'Pound', 'Aqua Orb', 50, 26, 0, 5, 40, 6, 'Close', 'Damage +1', 'Drain'),
	(23, 'Chew', 'Power', 'None', 'Jade Orb', 50, 49, 18, 4, 32, 6, 'Close', 'Damage +1, Hit +1', 'Slow'),
	(23, 'Butterfly', 'Intelligence', 'Magic', 'Aurora Orb', 29, 9, 34, 0, 43, 8, 'Long', 'Hit +1', 'Addled'),
	(24, 'Mosin', 'Power', 'Beat', 'Flare Bit', 15, 10, 2, 1, 50, 10, 'Close', 'Hit +1', 'Dizzy'),
	(24, 'Bass Blast', 'Intelligence', 'Wind', 'Aqua Bit', 20, 6, 25, 1, 47, 5, 'Mid', 'Guts Down +2', 'None'),
	(24, 'Back Spin', 'Power', 'Beat', 'Aurora Bit', 17, 18, 0, 3, 37, 6, 'Long', 'Varies', 'None'),
	(24, 'Drifting', 'Power', 'Earth', 'Jade Bit', 24, 15, 22, 7, 35, 10, 'Mid', 'Guts Down +1, Critical +1', 'Wince'),
	(24, 'Zero to Sixty', 'Power', 'Beat', 'Flare Stone', 60, 50, 3, 4, 42, 8, 'Long', 'Guts Down +1, Critical +1', 'Wince'),
	(24, 'Wohoho', 'Power', 'None', 'Aqua Stone', 40, 30, 30, 3, 36, 7, 'Close', 'Damage +1, Guts Down +1', 'None'),
	(24, 'Large Roller', 'Power', 'None', 'Jade Stone', 50, 47, 10, 6, 48, 9, 'Mid', 'Damage +1, Guts Down +1', 'Self-Destruct'),
	(24, 'Glider', 'Power', 'Beat', 'Aurora Stone', 36, 39, 8, 8, 32, 9, 'Long', 'Damage +1', 'None'),
	(24, 'Spin', 'Power', 'Beat', 'Aurora Orb', 32, 21, 1, 32, 48, 10, 'Mid', 'Hit +1', 'None'),
	(24, 'Cannonball', 'Power', 'Beat', 'Flare Orb', 48, 30, 6, 5, 53, 6, 'Mid', 'Damage +1, Critical +1', 'Dizzy'),
	(25, 'Judo Chop', 'Power', 'Beat', 'Jade Bit', 10, 12, 0, 2, 38, 8, 'Close', 'Hit +1, Damage +1 at Level 5', 'None'),
	(25, 'Plow Kick', 'Power', 'Beat', 'Aqua Bit', 20, 20, 10, 2, 37, 7, 'Mid', 'Damage +1', 'None'),
	(25, 'Heel Drop', 'Power', 'Beat', 'Aurora Bit', 14, 16, 3, 2, 38, 10, 'Close', 'Varies', 'None'),
	(25, 'Smash Fist', 'Power', 'Pound', 'Flare Bit', 18, 13, 5, 12, 42, 10, 'Close', 'Varies', 'None'),
	(25, 'Atomic Fist', 'Power', 'Pound', 'Aqua Stone', 32, 28, 20, 6, 40, 7, 'Mid', 'Varies', 'None'),
	(25, 'Spin Knuckle', 'Power', 'Beat', 'Flare Stone', 28, 29, 14, 8, 45, 9, 'Mid', 'Varies', 'None'),
	(25, 'Jumping Kick', 'Power', 'Pound', 'Jade Stone', 42, 35, 2, 26, 38, 9, 'Long', 'Varies', 'None'),
	(25, 'Head Clasher', 'Intelligence', 'Pound', 'Aurora Stone', 36, 16, 40, 4, 44, 9, 'Close', 'Varies', 'Addled'),
	(25, 'Phoenix Combo', 'Power', 'Beat, Flame', 'Flare Orb', 45, 38, 36, 21, 35, 8, 'Close', 'Varies', 'None'),
	(25, 'Hell Arrow', 'Intelligence', 'Wind, Heart', 'Jade Orb', 26, 25, 28, 4, 45, 9, 'Long', 'Varies', 'None'),
	(25, 'Eagle Rush', 'Power', 'Beat, Wind', 'Aurora Orb', 32, 16, 6, 2, 44, 9, 'Long', 'Varies', 'None'),
	(26, 'Tail Whip', 'Power', 'Beat', 'Aurora Bit', 10, 10, 5, 3, 42, 10, 'Mid', 'Hit +1', 'None'),
	(26, 'Bite', 'Power', 'Pound', 'Jade Bit', 23, 28, 12, 5, 35, 8, 'Close', 'Hit +1', 'None'),
	(26, 'Lick', 'Intelligence', 'Water', 'Aqua Bit', 15, 5, 28, 0, 45, 7, 'Mid', 'Hit +1', 'None'),
	(26, 'Suezo Beam', 'Intelligence', 'Flame', 'Flare Bit', 32, 26, 12, 15, 48, 7, 'Long', 'Damage +1', 'None'),
	(26, 'Deep Kiss', 'Intelligence', 'Heart', 'Aqua Stone', 35, 19, 38, 5, 50, 8, 'Close', 'Guts Down +2', 'None'),
	(26, 'Give Me', 'Power', 'None', 'Jade Stone', 43, 37, 37, 6, 40, 7, 'Close', 'Guts Down +1, Damage +1, Critical +1', 'Slow'),
	(26, '100 Fists', 'Power', 'Beat', 'Aurora Stone', 33, 40, 22, 12, 32, 10, 'Mid', 'Damage +1', 'None'),
	(26, 'Noise', 'Intelligence', 'Wind', 'Flare Stone', 50, 39, 29, 3, 46, 10, 'Mid', 'Guts Down +2, Critical +1', 'Dizzy'),
	(26, 'Hypnosis', 'Intelligence', 'Heart', 'Aqua Orb', 26, 8, 39, 0, 38, 7, 'Mid', 'Guts Down +2', 'Addled'),
	(26, 'Psychokinesis', 'Intelligence', 'Heart', 'Aurora Orb', 23, 16, 7, 6, 60, 5, 'Long', 'Damage +1', 'None'),
	(26, 'Meteor', 'Intelligence', 'Beat, Flame', 'Flare Orb', 50, 56, 10, 10, 40, 9, 'Long', 'Damage +1, Critical +1', 'None'),
	(27, 'Pokorin', 'Power', 'Beat', 'Jade Bit', 10, 7, 6, 1, 50, 10, 'Close', 'Critical +1, Hit +1', 'None'),
	(27, 'Ring Ring Hat', 'Power', 'Beat', 'Aurora Bit', 24, 22, 4, 3, 50, 10, 'Mid', 'Hit +1', 'None'),
	(27, 'Pokkorin', 'Power', 'Beat', 'Aqua Bit', 20, 27, 7, 3, 32, 8, 'Close', 'Damage +1', 'None'),
	(27, 'Cover Hit', 'Power', 'Beat', 'Jade Stone', 40, 31, 31, 3, 40, 6, 'Close', 'Damage +1, Guts Down +1, Critical +2', 'None'),
	(27, 'Dizzy', 'Intelligence', 'Heart', 'Aqua Stone', 26, 10, 36, 0, 45, 7, 'Mid', 'Damage +1', 'Addled'),
	(27, 'Aim Boom', 'Intelligence', 'Beat, Flame', 'Flare Stone', 32, 40, 10, 5, 35, 8, 'Long', 'Hit +1', 'None'),
	(27, 'Ringx3', 'Intelligence', 'Wind', 'Aurora Stone', 35, 23, 23, 3, 52, 5, 'Long', 'Guts Down +1, Critical +1, Damage +1', 'None'),
	(27, 'Ringx3', 'Intelligence', 'Wind', 'Aurora Stone', 35, 23, 23, 3, 52, 5, 'Long', 'Guts Down +1, Critical +1, Damage +1', 'None'),
	(27, 'Ringx3', 'Intelligence', 'None', 'Aqua Orb', 40, 35, 35, 10, 46, 7, 'Long', 'Guts Down +1, Damage +1', 'Self-Destruct'),
	(27, 'Do Mi So', 'Intelligence', 'Beat', 'Aurora Orb', 38, 50, 6, 3, 35, 8, 'Mid', 'Critical +1, Damage +1', 'None'),
	(27, 'Bowling', 'Intelligence', 'Beat', 'Jade Orb', 50, 40, 9, 3, 55, 10, 'Long', 'Damage +1', 'None'),
	(28, 'Tiger Spike', 'Power', 'Cut', 'Jade Bit', 10, 9, 3, 1, 45, 8, 'Mid', 'Hit +1', 'Wince'),
	(28, 'Tiger Charge', 'Power', 'Beat', 'Aqua Bit', 20, 14, 3, 5, 55, 5, 'Mid', 'Damage +1', 'Dizzy'),
	(28, 'Tiger Fang', 'Power', 'Pound', 'Flare Bit', 19, 23, 5, 5, 32, 6, 'Close', 'Hit +1', 'None'),
	(28, 'Somersault', 'Power', 'Beat', 'Aurora Bit', 24, 20, 6, 13, 50, 7, 'Close', 'Critical +2, Guts Down +1', 'None'),
	(28, 'Tiger Step', 'Power', 'Cut', 'Aurora Stone', 40, 40, 9, 35, 36, 6, 'Long', 'Critical +2, Hit +1', 'None'),
	(28, 'Howl', 'Intelligence', 'Heart', 'Aqua Stone', 32, 13, 42, 2, 50, 10, 'Long', 'Hit +1', 'None'),
	(28, 'Thunder Bash', 'Intelligence', 'Thunder', 'Flare Stone', 45, 34, 29, 5, 45, 10, 'Long', 'Critical +2, Guts Down +1', 'Stun'),
	(28, 'Tiger Combo', 'Intelligence', 'Thunder, Cut', 'Jade Stone', 50, 42, 18, 10, 48, 7, 'Mid', 'Critical +1, Guts Down +1', 'Stun'),
	(28, 'Moon Assault', 'Power', 'Beat', 'Jade Orb', 50, 48, 6, 5, 50, 10, 'Long', 'Damage +1, Guts Down +1', 'None'),
	(28, 'Tiger Force', 'Intelligence', 'Thunder', 'Aurora Orb', 12, 0, 0, 0, 73, 4, 'Any', 'Nothing', 'None'),
	(29, 'Single Shot', 'Power', 'Pound', 'Jade Bit', 10, 12, 0, 3, 48, 4, 'Close', 'Damage +1', 'None'),
	(29, 'Double Summer', 'Power', 'Beat', 'Aurora Bit', 21, 30, 3, 10, 36, 7, 'Close', 'Damage +1', 'None'),
	(29, 'Sonic Knife', 'Power', 'Cut', 'Flare Bit', 18, 17, 2, 6, 56, 8, 'Mid', 'Hit +1, Critical +1', 'None'),
	(29, 'Leg Arc', 'Power', 'Beat', 'Aqua Bit', 13, 10, 13, 2, 44, 8, 'Close', 'Hit +1', 'Wince'),
	(29, 'Meteor Drive', 'Power', 'Beat', 'Aurora Stone', 35, 48, 22, 5, 32, 6, 'Long', 'Hit +1, Critical +1', 'None'),
	(29, 'Rising Rave', 'Power', 'Cut', 'Flare Stone', 42, 40, 13, 7, 51, 7, 'Close', 'Hit +1, Critical +1', 'None'),
	(29, 'Reverse Raid', 'Power', 'Cut', 'Jade Stone', 39, 32, 4, 10, 62, 8, 'Mid', 'Damage +1', 'None'),
	(29, 'Axes Ballet', 'Power', 'Cut', 'Aqua Stone', 50, 47, 5, 35, 45, 10, 'Long', 'Damage +1', 'None'),
	(29, 'Assault Dance', 'Power', 'None', 'Flare Orb', 24, 27, 4, 3, 48, 10, 'Mid', 'Hit +1', 'None'),
	(29, 'Far Sight', 'Intelligence', 'Heart', 'Jade Orb', 30, 0, 0, 0, 41, 8, 'Any', 'Hit +1', 'Despair'),
	(29, 'Stunner Blitz', 'Intelligence', 'Thunder', 'Aurora Orb', 22, 16, 8, 5, 51, 7, 'Long', 'Damage +1', 'Stun'),
	(29, 'Mirage Shift', 'Power', 'Special', 'Aqua Orb', 5, 0, 0, 0, 100, 5, 'Any', '-1 Guts', 'Changes close ranged attacks to long and viceversa.'),
	(30, 'Tail Attack', 'Power', 'Beat', 'Aqua Bit', 15, 10, 4, 2, 50, 10, 'Close', 'None', 'None'),
	(30, 'Fireball', 'Intelligence', 'Flame', 'Flare Bit', 24, 18, 12, 4, 44, 10, 'Long', 'Hit +1', 'None'),
	(30, 'Jump Kick', 'Power', 'Beat', 'Aurora Bit', 18, 16, 4, 10, 40, 10, 'Close', 'Critical +3', 'None'),
	(30, 'Tackle', 'Power', 'Beat', 'Jade Bit', 21, 22, 4, 4, 36, 6, 'Mid', 'Damage +1', 'None'),
	(30, 'Tail Slap', 'Power', 'Beat', 'Aqua Stone', 38, 27, 8, 12, 49, 8, 'Long', 'Critical +1, Hit +1', 'None'),
	(30, 'Tear Bite', 'Power', 'Pound', 'Flare Stone', 34, 50, 9, 12, 32, 6, 'Close', 'Critical +1, Hit +1', 'None'),
	(30, 'Charge', 'Power', 'Beat', 'Jade Stone', 50, 38, 9, 9, 45, 10, 'Mid', 'Damage +1', 'Dizzy'),
	(30, 'Kick Lift', 'Power', 'Beat', 'Aurora Stone', 42, 21, 35, 2, 48, 8, 'Close', 'Damage +1', 'Addled'),
	(30, 'Spin Tail', 'Power', 'Beat', 'Aqua Orb', 32, 22, 5, 4, 55, 9, 'Mid', 'Hit +1, Critical +1', 'None'),
	(30, 'Great Fire', 'Intelligence', 'Flame', 'Flare Orb', 45, 29, 26, 19, 43, 9, 'Long', 'Damage +1', 'None'),
	(30, 'Spiral', 'Intelligence', 'Heart', 'Jade Orb', 28, 7, 37, 0, 48, 6, 'Close', 'Guts Down +2', 'Addled'),
	(30, 'Hero Kick', 'Power', 'Beat', 'Aurora Orb', 30, 26, 8, 12, 40, 9, 'Mid', 'Hit +1', 'None');

INSERT INTO Characteristic (Characteristic, Description) VALUES
        ('Active', '"I can''t just sit around all day..."'),
        ('Aggressive', '"Something you wanted to say?"'),
        ('Aloof', '"Oh, nothing..."'),
        ('Aquaphobic', 'Hates to even see water. Swimming is out of the question.'),
        ('Armor', 'Damage is decreased, but has a hard time dodging.'),
        ('Arthritis', 'Shoulders hurt, and is easily irritable.'),
        ('Bashful', '"....."'),
        ('Brave', '"I won''t run from this battle."'),
        ('Bruise', 'A bruise incurred in battle. Should heal by the next week.'),
        ('Burn', 'Burns from battles. Should heal by the next week.'),
        ('Calm', '"Let''s calm down, and reassess things."'),
        ('Careful', '"Look both ways... Watch that step..."'),
        ('Charming Eye', 'Increases the effect of Charm attacks.'),
        ('Cheerful', '"Singing and dancing is pure paradise."'),
        ('Childish', '"Do I have to?"'),
        ('Chlorophyll', 'Performs photo-synthesis during rest, to self-heal.'),
        ('Clean', '"I need to take a bath everyday."'),
        ('Cold', 'Wind bring many diseases. Let''s be careful.'),
        ('Cold Limbs', 'Weak against cold. Hands and feet start to hurt.'),
        ('Combative', '"Doesn''t anyone want to fight me?"'),
        ('Confident', '"I won''t lose. No matter what!"'),
        ('Contrary', '"What? I''d rather not do that."'),
        ('Cool', '"Hrm…"'),
        ('Dark Aura', 'Traps soul in darkness. Less prone to enemy Heart attacks.'),
        ('Defense Roll', 'Reduces damage from throwing attacks.'),
        ('Difficult', '"... Yeah, what''s your problem?"'),
        ('Dim-witted', '"Oh?... I didn''t realize that..."'),
        ('Dimples', 'Charm point that can be seen when laughing.'),
        ('Directionless', 'It''s an adventure no matter where it goes.'),
        ('Dry Skin', 'Fatigue and stress are the enemies of beauty.'),
        ('Earth Secrets', 'Greatly increases the damage done by Earth attacks.'),
        ('Earth Wisdom', 'Slightly increases the damage done by Earth attacks.'),
        ('Easily Tired', 'Doesn''t feel well, and gets tired easily than usual.'),
        ('Easygoing', '"I''m sure it''ll turn out okay."'),
        ('Eats Anything', 'Loses preference for foods, but any food eaten is okay.'),
        ('Energetic', '"Yeah, that''s the way!"'),
        ('Extra Teeth', 'Charm point that can be seen when laughing.'),
        ('Faithful', '"Please tell me anything you want me to do."'),
        ('Fast Footwork', 'Dodges attacks more often, but Hit damage increases.'),
        ('Fearless', '"It''s not that strong, is it?"'),
        ('Fire Wisdom', 'Increases the damage done by Flame attacks.'),
        ('Flame Secrets', 'Greatly increases the damage done by Flame attacks.'),
        ('Flexible Tail', 'Increases the accuracy rate of Tail attacks.'),
        ('Gluttonous', '"I want to eat some more..."'),
        ('Gourmet', 'Becomes picky with its food.'),
        ('Greedy', '"I want this. Oh, and this too."'),
        ('Groovy Moves', 'Increases effects of Dance attacks'),
        ('Hard Scales', 'Damage is decreased, but it has a hard time dodging.'),
        ('Hay Fever', 'Sneezes a lot during the spring, and is easily stressed.'),
        ('Heart Secrets', 'Greatly increases the Guts damage from Heart attacks.'),
        ('Heart Wisdom', 'Slightly increases the Guts damage done by Heart attacks.'),
        ('Heat-Proofing', 'A special covering that blocks out heat.'),
        ('Hesitant', '"I don''t think I''m ready just yet."'),
        ('High Output', 'Increases damage from Beam attacks.'),
        ('Honest', '"Yes, sir. I understand."'),
        ('Honorable', '"I will swear upon my name."'),
        ('Hypotension', 'Doesn''t wake up easily. Ugh, morning already?'),
        ('Hysterical', '"What!?!?!"'),
        ('Ice Secrets', 'Greatly increases the damage done by Ice attacks.'),
        ('Ice Wisdom', 'Slightly increases the damage done by Ice attacks.'),
        ('Illusion Cape', 'Confuses the enemy, making dodging easier.'),
        ('Impatient', '"I don''t believe'),
        ('Independent', '"I am unique. No one is quite like me."'),
        ('Indifferent', '"Say what you will."'),
        ('Indignant', '"I don''t know! Stop bothering me!"'),
        ('Injury', 'Damage from battles. Should heal by the next week.'),
        ('Insulation', 'A special covering that doesn''t allow electricity through.'),
        ('Intuitive', '"You''re not telling me everything..."'),
        ('Iron Fists', 'Slightly increases the damage done by fists.'),
        ('Iron Heart', 'Toughens the monster so it doesn''t get tired easily.'),
        ('Jell Body', 'Reduces damage from Hit attacks'),
        ('Lazy', '"Let me sleep a little bit more..."'),
        ('Life Secrets', 'Significantly increases the damage from Life attacks.'),
        ('Life Wisdom', 'Slightly increases the damage done by Life attacks.'),
        ('Light Aura', 'Less susceptible to enemy Magic attacks.'),
        ('Loud Voice', 'Slightly increases the damage done by voice attacks.'),
        ('Ltng. Secrets', 'Greatly increases the damage done by Lightning attacks.'),
        ('Ltng. Wisdom', 'Slightly increases the damage done by Lightning attacks.'),
        ('Lump', 'A lump incurred in battle. Should heal by the next week.'),
        ('Lung Capacity', 'Slightly increases the damage done by Breath attacks.'),
        ('Magic Secrets', 'Greatly increases the damage done by Magic attacks.'),
        ('Magic Wisdom', 'Slightly increases the damage done by Magic attacks.'),
        ('Migrane', 'A bad headache makes a monster irritable.'),
        ('Modest', '"No... I''m not very good..."'),
        ('Narcissistic', '"I am absolutely gorgeous, aren''t I?"'),
        ('Nearsighted', 'Can see things up close, but can''t see well far away.'),
        ('Nervous', '"I''m still worried about that thing..."'),
        ('Nice', '"May everyone live happily."'),
        ('Normal', '"Everything''s fine. Just fine."'),
        ('Optimistic', '"Well, let''s just give it a try, then"'),
        ('Passionate', '"Arrgh, let''s do it!"'),
        ('Perceptive', '"Hey, I found some money!"'),
        ('Perfectionist', '"Gotta do it right or not at all..."'),
        ('Pessimistic', '"Am... Am I going to be okay?"'),
        ('Pheromones', 'Increases the chance of Charming the opponent.'),
        ('Pride', '"I deserve better than most monsters."'),
        ('Quiet', '"I like to avoid conflicts."'),
        ('Radar', 'Increases the chance of hitting opponent with attacks.'),
        ('Refined', '"If you''ll excuse me, I must be going."'),
        ('Relaxed', '"Break time! Break time!"'),
        ('Reliable', '"No need to rush. Take it slowly."'),
        ('Resists Cold', 'Perfectly fine, even in cold weather.'),
        ('Resists Heat', 'Doesn''t mind hot regions.'),
        ('Resists Ltng', 'Reduces damage from Lightning.'),
        ('Resists Magic', 'Reduces damage from Magic attacks.'),
        ('Resists Water', 'Reduces damage from Water attacks.'),
        ('Resists Wind', 'Reduces damage from Wind attacks.'),
        ('Rock Head', 'Increases damage from head attacks. No relation to IQ.'),
        ('Selfish', '"I get mad when you don''t listen to me."'),
        ('Sensitive', '"How cruel! My heart of glass has been shattered!"'),
        ('Serious', '"I''ll try my best."'),
        ('Sharp Claws', 'Slightly increases damage done by nail attacks.'),
        ('Sharp Ears', 'Doesn''t miss a sound!'),
        ('Sharp Edge', 'Increases damage done by weapon attacks.'),
        ('Sharp Eyes', 'Increases the chance attacks connecting.'),
        ('Sharp Fangs', 'Slightly increases damage done by teeth attacks.'),
        ('Sharp Horns', 'Slightly increases damage done by horn attacks.'),
        ('Show-off', '"Heh, heh, heh. Watch this one..."'),
        ('Shy', '"..... Oh, nothing."'),
        ('Sleepless', 'Can''t sleep well, so rest time does not help much.'),
        ('Slow', '"Uh..."'),
        ('Small Stomach', '"I don''t have much of an appetite."'),
        ('Sniper', 'Increases the chance of hitting the enemy with Throwing moves.'),
        ('Snoring', 'Very troublesome to those asleep nearby, but not the snorer.'),
        ('Soft Skin', 'Skin is soft and feels good to touch.'),
        ('Sore Loser', '"I won''t let you win [and] just walk away..."'),
        ('Split Ends', 'Fatigue and stress are the enemies of beauty.'),
        ('Spoiled', '"Play with me, play with me..."'),
        ('Stinky Feet', 'Kinda gross when you get kicked by it.'),
        ('Stoic', '"I still need to train harder."'),
        ('Stone Body', 'Reduces damage, but makes dodging more difficult.'),
        ('Strong Heart', 'Reduces damage from Heart attacks.'),
        ('Stubborn', '"I don''t care. I know I''m right."'),
        ('Stuffy Nose', 'Has a hard time breathing and is easily irritated.'),
        ('Sweaty', 'Doesn''t like hot regions, but doesn''t hate them, either.'),
        ('Sweet Smell', 'A strange sweet smell that clouds the minds of enemies.'),
        ('Sweet Voice', 'Increases the success rate of Singing attacks.'),
        ('Thick Fur', 'Very warm-looking fur.'),
        ('Thirsty', 'Can''t function right without humidity'),
        ('Timid', '"No way... that''s scary."'),
        ('Tone-deaf', 'Decreases the success rate of Singing attacks.'),
        ('Touchy', '"What''d you say?!"'),
        ('Tough Skin', 'Reduces damage, but makes dodging more difficult.'),
        ('Unfriendly', '"What''s so funny?"'),
        ('Unselfish', '"''Something I want?'' No, not really."'),
        ('Vegetarian', 'Can eat meat, but chooses not to.'),
        ('Water Secrets', 'Greatly increases the damage done by Water attacks.'),
        ('Water Wisdom', 'Slightly increases the damage done by Water attacks.'),
        ('Waterproofing', 'A special covering that doesn''t allow water through.'),
        ('Weak Heart', 'More susceptible to Heart attacks.'),
        ('Weak v. Cold', 'Hates cold regions.'),
        ('Weak v. Heat', 'Prefers to avoid hot regions.'),
        ('Weak v. Ltng', 'Increases damage from Lightning.'),
        ('Weak v. Magic', 'Increases damage from Magic attacks.'),
        ('Weak v. Water', 'Increases damage from Water attacks.'),
        ('Weak v. Wind', 'Increases damage from Wind attacks'),
        ('Weirdo', '"?"'),
        ('Whimsical', '"I don''t feel like working this week."'),
        ('Wind Secrets', 'Greatly increases the damage done by Wind attacks.'),
        ('Wind Wisdom', 'Slightly increases the damage done by Wind attacks.');


INSERT INTO Derivation (Derivation) VALUES 
	('Baku'),
	('Beaklon'),
	('Colorpandora'),
	('Dragon'),
	('Dakkung'),
	('Durahan'),
	('Gitan'),
	('Golem'),
	('Hare'),
	('Hengar'),
	('Jell'),
	('Joker'),
	('Lesione'),
	('Mew'),
	('Mocchi'),
	('Mogi'),
	('Momo'),
	('Naga'),
	('Octopee'),
	('Ogyo'),
	('Pancho'),
	('Pixie'),
	('Plant'),
	('Psiroller'),
	('Raiden'),
	('Suezo'),
	('Suzurin'),
	('Tiger'),
	('Zan'),
	('Zoom');

INSERT INTO Monster (Monster, DerivationID, RegionID, Description) VALUES
	('Baku', 1, 1, 'A big furry loveable moster with a huge appetite. Contrary to its looks, it is actually very agile.'),
	('Electrieel', 1, 2, 'This monster mutated from a huge Lantern Fish. They say lightning hitting the fish is what triggered the transformation.'),
	('Kobu', 1, 3, 'They say at the top of its head you can find the legendary "water of happiness," but no one has been blessed by it yet.'),
	('Leon', 1, 4, '''Sleeping Lion'' is the perfect phrase to describe Leon, because it is asleep just about all the time. Maybe a little bit too much.'),
	('Baksheesh', 1, 5, 'The tusks on the lower jaw can throw anyone. Only rarely does this Baku turn violent, but once it starts to turn, no one can stop it.'),
	('Beeslim', 1, 6, 'Although it often works out, it is not seeing much result. It is still looking for the dumbbells it lost last week.'),
	('Avalanche', 2, 1, 'The horn is as cold as an icicle and radiates cold air. When two horns of these monsters touch, they freeze together!'),
	('Scissors', 2, 2, 'The scissor-shaped horns on its head cut anything. If it abuses the horns, they fall off, but that is okay because they''ll grow back quickly.'),
	('Scorpi', 2, 3, 'This savage monster has poison at the tip of its horn. However, about 10 of them die each year due to their own poison, which is kind of silly...'),
	('Mose', 2, 4, 'Because of its huge shoulders and horn that can act as a straw to suck honey directly from a beehive, it has come to love sweet things.'),
	('Beaklon', 2, 5, 'Protected by strong armor, equipped with powerful muscles, this monster also has the power of flight. Some say their intelligence is rather low, but that isn''t really true.'),
	('Bealock', 2, 6, 'It is a strong warrior, but it has one weak point: it cannot swim because its body is made of stone.'),
	('Bercouger', 2, 6, 'Forever the rival of Beaklon, its pincers are just as powerful as Beaklon''s horn.'),
	('Cantalos', 2, 6, 'Cantalos emits a sweet odor from its body to confuse its enemies. Don''t go too close, because the smell will stay with you for days!'),
	('Tanklon', 2, 6, 'Enthusiastic fans, called the "Tanklon Battalion," are crazy about this monster. I think it''s that cool shade of green.'),
	('Koronit', 3, 1, 'When the weather becomes cold, its fur becomes thicker. You can tell which region this monster is from by looking at the thickness of its fur.'),
	('Fukazukin', 3, 2, 'Its shape came to resemble a shark after it adapted to the marine environment. It also need not worry about getting eaten by a shark this way...'),
	('Korodango', 3, 3, 'If you poke this monster, it curls up to protect itself. Although it could probably move faster in that shape, it never does. Maybe it hurts to roll?'),
	('Colorpandora', 3, 4, 'Cool, Merry, and enthusiastic; Each of the three has a different characteristic. Humans could learn from the way these three support each other.'),
	('Marimba', 3, 5, 'Easily mistaken for a tree, people often try to cut them down. But every time, the three bind tightly together and they are saved.'),
	('Kapukkoro', 3, 6, 'People say that watching Kapukkoro will cure colds and other common ailments. Kapukkoro do not appreciate this kind of superstition.'),
	('Shimurug', 4, 1, 'This Dragon is said to be the guardian god of this region. It is strong against the cold with its thick fur, and its breath is a special flame called ''Ice Breath.'''),
	('Zaratan', 4, 2, 'This creature can swim in the water as if it were flying, and its blue skin is rough like a shark''s. Don''t touch it - you''ll hurt your fingers.'),
	('Druger', 4, 3, 'This divine dragon used to be called Pi-Long. It has been fighting so long it has forgotten anything else exists in the world.'),
	('Fafneel', 4, 4, 'This smart Dragon first immobilizes its opponent with the poisonous thorns on its jaw. However, sometimes it accidentally pricks itself…'),
	('Dragon', 4, 5, 'In the future, this monster will be a legend. Although its power is virtually limitless, this power is said to be hard to release.'),
	('Grupus', 4, 6, 'Grupus was born when moss grew on a Dragon hibernating underground. It can photosynthesize, so it can live for many days without eating.'),
	('Kujata', 4, 6, 'This mysterious Dragon is said to have come from the other side of the moon, though that is not really true. It has a bad temper and is hard to train.'),
	('Tigon', 4, 6, 'Imitating bamboo, a dragon like an illusion you can''t really see. I can''t tell if it''s only sleeping - there is still no one who knows for sure.'),
	('Kung-Fu Dragon', 4, 6, '''I have never seen Kung-Fu get hit by an enemy,'' says a Breeder that trained one. (and she''s not lying!)'),
	('Dakkung', 5, 1, 'A romantic, despite its voice and moves, it fancies itself beautiful. Its ''Self-Bomb'' is a must-see. Beyond this we don''t know much about it.'),
	('Wakkung', 5, 2, 'Wakkungs knows the rings is fashionable. Although they say it change their patterns itself, no one has seen it in person.'),
	('Karakarakkung', 5, 3, 'For some reason, Karakkung is afraid of triangles. When it sees one, it starts meditating. I wonder why?'),
	('Tokunbokun', 5, 4, 'It used to have beautiful skin until it got a tan. Now it is so sad it just looks at itself in the water and cries.'),
	('Dokkung', 5, 5, 'It polishes its acorn body until it is shiny. The woodland creatures then use it as a mirror.'),
	('Windukkung', 5, 6, 'This creature has no sense of direction, which led to the proverb "Don''t ask Windukkung for directions." It often gets lost.'),
	('Eggukkung', 5, 6, 'A rumor suggests there is a raw Eggukkung and a boiled Eggukkung, though it''s probably just a bad joke by Breeders who missed breakfast.'),
	('Planekkun', 5, 6, 'This mystery monster is said to have been bathed in starlight for 1,000 years. Its secrets have yet to berevealed.'),
	('Cookun', 5, 6, 'His goal is to become the world''s best chef, so every day he is busy studying. But, the truth is that his own body is the most delicious thing.'),
	('Highlander', 6, 1, 'An armor monster adapted to the snow. They say it used to be the soul of a warrior who died on a quest for a legendary place.'),
	('Drydon', 6, 2, 'The reincarnation of a man born, raised, and killed at sea. The ax of blue metal is said to be strong enough to slice into other dimensions.'),
	('Galooda', 6, 3, 'A quick and agile warrior with a soul as hot as the desert sun. It used to fly freely in the air.'),
	('Ruin Sector', 6, 4, 'The armor of Ruin Sector, also known as ''Neck Slicer,'' was possessed by the soul of a monster. We still don''t know what happened to Ruin.'),
	('Durahan', 6, 5, 'This monster took over armor that is said to have belonged to a Tochikan warrior. A rumor says the sword is alive, but no one knows for sure.'),
	('Cabaree', 6, 6, 'Cabaree came from a different world called Worn Hope. Its ''Superior Lance'' technique is touted as an art form.'),
	('Masala', 6, 6, 'It used to be a warrior of light, but after it found a demon sword, its mind was lost, and its body color became dark.'),
	('Forestra', 6, 6, 'The ancient White Knight. Its sword has the magic power of repelling evil. Many have witnessed it sitting quietly in the woods.'),
	('Enki', 6, 6, 'There once was a country that was at war with Tochika. Enki is said to be the armor used in that country, feared because it is cursed.'),
	('Gitan', 7, 1, 'Gently floating along with its big ears and big tail, this monster looks very mysterious. I wonder why its eyes are always so sullen...'),
	('Oltan', 7, 2, 'I''ve no idea what it is thinking, but it does have cute eyes. Careful, if you let your guard down near it, you''re liable to get poked!'),
	('Cactun', 7, 3, 'This cactus always stands silently, but sometimes it just has to jump. It''s affectionate toward people, but nothing can save the person it approaches...'),
	('Coltan', 7, 4, 'Despite the glowing body, sharp eyes, and stern looks, it''s really just lonely, and wants some friends to play with.'),
	('Ootan', 7, 5, 'This monster was raised in the forest as a wolf. It howls at the full moon with its big mouth. Isn''t that a little annoying?'),
	('Maestan', 7, 6, 'Because it''s busy listening to all the music in the world, it is always sleep-deprived. It may look unpleasant, but it''s really a kind musician at heart.'),
	('Elebus', 8, 1, 'This shiny and highly visible Golem is made entirely of ice. It is very popular during hot summer days.'),
	('Kaio', 8, 2, 'It is said this Golem is modeled after a Sea God in a fairy tale. This is the only Golem not afraid of water.'),
	('Lapislatel', 8, 3, 'Called the ''Desert Castle,'' this Golem has high defense. When traveling in the desert, Breeders sometimes bring one instead of a tent.'),
	('Lemlaria', 8, 4, 'This golden Golem has been blessed by the mysterious powers of the deep forest. It looks golden because of this magical blessing.'),
	('Golem', 8, 5, 'This Golem is a kind monster who loves to be one with nature. However, in battle it will fight furiously with powerful techniques.'),
	('Ormeka', 8, 6, 'This ancient and mysterious Golem was just recently discovered. Its body was covered with moss, so it must have been there awhile.'),
	('Nedel', 8, 6, 'This ecological Golem likes places with lots of wind from which it can generate energy. Kids love it because it looks like a toy.'),
	('Baum', 8, 6, 'This Golem is made from a 1000-year-old oak tree. Birds build nests among the leaves.'),
	('Oh', 8, 6, 'Even among Golems, which pride themselves on their strength, this flamboyant egotist is noticeably strong. Is it for real?'),
	('Strawberry', 9, 1, 'Strawberry is a friendly and spoiled baby. Popular as a pet, its favorite food is the strawberry, as you might have guessed.'),
	('Spearmint', 9, 2, 'The twisty thing on its head is not hair, but a shell. It is so fashionable that it goes underwater to put on these stylish things.'),
	('Jiro', 9, 3, 'This monster can curl up into a highly armored ball. But if the wind blows when it''s like this, it will be rolling around all over the place.'),
	('Scurfy', 9, 4, 'It always has a cynical smile, but really it''s very kind. It is very good-looking, too, brushing its eyebrows every morning until they are perfect.'),
	('Hare', 9, 5, 'Famous for its long ears and cute moves, Hare is always energetic. Watch for its powerful Spin Fist!'),
	('Panthy', 9, 6, 'Wearing today''s most stylin'' outfit, Panthy is known among young Breeders for its charisma.'),
	('Honey', 9, 6, 'Honey is famous for its cute hips and round ears. No matter how hard it flaps its wings, it can only fly a couple inches at most.'),
	('Mumm', 9, 6, 'Mumm always wakes up early to put on its dress and apron. It is a hard worker, always preparing meals.'),
	('Metanix', 10, 1, 'A cold-weather type Henger equipped with skis. It must have patrolled the mountainous regions frequently.'),
	('Skullwave', 10, 2, 'This monster is said to bear the soul of the legendary pirate Edgar. However, no one knows anything about this Edgar, so....'),
	('Hengar', 10, 3, 'A mysterious robot monster made by an ancient lost civilization. Its mechanisms could not be understood for a very long time.'),
	('Dark-Bringer', 10, 4, 'Its hand is a knife, and it can see in the dark. Thus, people say that this monster must have been an assassination device in ancient times.'),
	('Kyuza', 10, 5, 'This is the most common type of Henger that was manufactured. Different color versions and custom types can also be seen.'),
	('Avaoner', 10, 6, 'It can fly swiftly in the air using its large wings. On the ground, however, its wings get stuck in alleys and doorways. Very inconvenient.'),
	('Vulcan', 10, 6, 'They say this was the champion machine in the Henger fights long ago that made the Ancients go crazy.'),
	('Burstliner', 10, 6, 'The heaviest of all the Hengers. It is good at making roads and tunnels, and its earthshaking attacks are very powerful.'),
	('Locomotive', 10, 6, 'It imitated a ''locomotive'' which it saw in a foreign country. Its performance is the same as a normal Henger.'),
	('Marshmallow', 11, 1, 'They are great hunters. The white Jell body blends in perfectly with the snow as they sneak silently up and fire their Jell Cannons.'),
	('Jell', 11, 2, 'These Jell creatures have avoided contact with humans, and thus have not taken on a human shape. This is the true shape of a Jell.'),
	('Carame', 11, 3, 'Its body is covered with sand, but the inside is full of Jell water. They sometimes help desert wanderers with this water.'),
	('Kakao', 11, 4, 'Thanks to the heat of the jungle, Kakao is very easy-going. On a moonlit night, you might be able to see its Jell Dance, though you''ll lose Guts Points.'),
	('Kuloro', 11, 5, 'The green Jell body is full of chlorophyll. They say it can live for a long time on just water and light.'),
	('Puddingel', 11, 6, 'A very tasty-looking monster. It''s true what they say, that the Tochikans invented pudding after first seeing a Puddingel.'),
	('Joker', 12, 5, 'When you see it, run away as fast as you can. It is a messenger of Death, or maybe it is Death itself. Its name is Death Joker. Protect yourself.'),
	('Magi', 12, 6, 'No one knows where it is from. If it proposes a bet using its cards, don''t accept. If you lose the bet, you''ll lose your life. Watch out!'),
	('Biansnow', 13, 1, 'Be careful not to mess with its hairstyle, because it gets very upset. Make sure you redo its hair after every battle.'),
	('Lesione', 13, 2, 'This is a spoiled baby monster whose cry for its mother caused it to become a Lesihorne. Other Lesiones start crying when they hear it cry.'),
	('Sandlessie', 13, 3, 'This monster was thought of as royal and noble since it used to carry the King on its back. You can see this in the insignia on its forehead.'),
	('Hibis', 13, 4, 'The flower on its tail grows bigger as Hibis gets older. Perfumes created from this flower are a special product made solely in Kalaragi.'),
	('Grilief', 13, 5, 'The leaf is for camouflage reasons. Its hiding ability is so great that even their Breeders can''t find them.'),
	('Coral', 13, 6, 'Its texture is soft like a sponge. It feels so good you want to sleep on its back.'),
	('Diamante', 13, 6, 'The horns that grow out every year become valuable gemstones. Many wedding rings are made from them. Girls often long for one.'),
	('Seapea', 13, 6, 'Very gentle and kind, it''s an ideal playmate for children. When it is in a good mood, it will show you some tricks.'),
	('Metal Head', 13, 6, 'It usually saves energy for upcoming fights by doing nothing. A very clever monster...'),
	('Konta', 14, 1, 'Konta thinks it can do anything with just a piece of a leaf. It often tries to use the leaf as money and gets in trouble for it.'),
	('Tortboy', 14, 2, 'This is the most relaxed of all Mews, and because of this many want it as a pet. It can move surprisingly fast sometimes, though.'),
	('Mewkiri', 14, 3, 'Mewkiri thinks it is a giraffe, so they don''t like being called a monster. Nonetheless, it continues to eat fish rather than grass.'),
	('Mew', 14, 4, 'This monster likes to sing so much that at some point it started carrying a microphone around. Lately it''s been wanting to try acting, too.'),
	('Bambiimew', 14, 5, 'This Mew has adapted to a forest setting. The pattern on its back resembles light streaming through the leaves of a tree, for great camouflage.'),
	('Boochin', 14, 6, 'Its big nose can vacuum up anything. Its power is so great, it once sucked up all the mushrooms in the Morx Forest.'),
	('Kero', 14, 6, 'Kero adapted to a water environment differently than Tortboy. It is said it sometimes sings a song to bring rain.'),
	('Mewsneak', 14, 6, 'A thief who disturbs the city every night, stealing instead of working. If she doesn''t watch her figure, she soon won''t be able to fit into that fur coat.'),
	('Mew-J', 14, 6, 'A Mew that loves basketball but has no real skills. When it decides to dunk, it always end up going through the hoop rather than the ball.'),
	('Mewseijin', 14, 6, 'Its body is covered with a special skin, and its large eyes are always shining. There are rumors that it''s from another planet, or that is really a machine.'),
	('Sherbet', 15, 1, 'Raised as a seal, this monster stayed with them until one day it realized the truth. The tears shed then are still visible.'),
	('Isobe', 15, 2, 'Isobe was the most famous creature in Goat, until they found Octopee. Go Isobe! Show them you''re still the best!'),
	('Warabi', 15, 3, 'Its skin is actually covered with sand. Because it carefully keeps itself covered, no one knows the real color of its skin.'),
	('Koloro', 15, 4, 'Koloro has lived in Kalaragi for a long, long time. Every year at the famous Koloro Festival, you can see the Koloro Dance. It''s fun.'),
	('Mocchi', 15, 5, 'Its cute moves and sticky skin make it popular among breeders. The cute, squeaky voice is another reason to love it.'),
	('Succhi', 15, 6, '''Welcome!'' Succhi says this all the time, but it doesn''t make much sense. It had two friends, but after a fight, they left. It likes to wake up early.'),
	('Sumocchi', 15, 6, 'He has mastered the Eastern art of wrestling called ''Sumo.'' He retired the rank of Yokozuna (champion), and now entered the arena of Monster Battles!!'),
	('Cosmocchi', 15, 6, 'It was predicted this Mocchi will one day save the world. But it doesn''t know that yet, and lives every day peacefully, calm and relaxed.'),
	('Fleece', 16, 1, 'This monster is good at winter sports and is often called ''Prince of the Snow Field.'' However, the best thing about it is its ability to make a snowhouse.'),
	('Offshore', 16, 2, 'This one likes to sit underwater, moving along with the current. Unfortunately, sometimes fish lay eggs in its hair.'),
	('Mogi', 16, 3, 'It uses the big drill on its head to dig through the ground on a 16-beat rhythm. It''s kind of like a mole.'),
	('Tigre', 16, 4, 'This monster is wild, as its look suggests. Many breeders fear this monster. But you seldom meet these, so don''t worry.'),
	('Bosco', 16, 5, 'This monster likes reed whistles, and walks around whistling all the time. Since it tries to use all kinds of grasses, sometimes its lips get swollen.'),
	('Maharajan', 16, 6, 'This monster does mystic moves called ''Yogar.'' They say that even if it is hurt, using ''Yogar'' it can heal quickly. Can this be true?'),
	('Blackie', 16, 6, 'Living on the streets, it is never without its sunglasses. Shrewder than the other Mogis, it often ditches training.'),
	('Pepe', 17, 1, 'Pepe is popular with children because of its cute walk, but Pepe actually does not like kids much because they always mess up its neat hair.'),
	('Lulu', 17, 2, 'Sometimes you will find a wild Lulu while fishing. Fisherpeople love to see Lulu''s cute face emerging from the water.'),
	('Zaza', 17, 3, 'While you can often see Zaza having fun, rolling down the sand dunes, no one has ever seen Zaza climbing back up the dunes...'),
	('Kiki', 17, 4, 'Mischievous Kiki likes to jump from tree to tree and drop nuts on people walking below. Watch out!'),
	('Momo', 17, 5, 'Momo likes to be calm and move at its own pace. It always carries that large walnut for its aroma-therapeutic effects.'),
	('Panko', 17, 6, 'Panko is an unconventional dresser and loves to travel. It might be coming to your town soon!'),
	('Ryozan', 18, 1, 'Sometimes, this monster starts hibernating before the winter comes, which is why many Breeders have given up on this monster.'),
	('Merman', 18, 2, 'With the gills on its breast, it can breathe underwater. This monster sees itself as a mermaid, but others have trouble with that idea.'),
	('Aspis', 18, 3, 'As the deadly colors on its skin show, it has poisonous fangs, claws, and tail. They say it cannot help dancing when it hears a flute melody.'),
	('Naga', 18, 4, 'Although they say this is the most ferocious monster of all, it is actually quite careless. It often fails to catch its prey.'),
	('Viper', 18, 5, 'It claims to be vegetarian, but, as is the case with humans, that doesn''t mean it''s true.'),
	('Ekidonna', 18, 6, 'A black Naga that came from the darkness. Its powers are unknown. A very mysterious monster.'),
	('Eega', 18, 6, 'This eerie eel-shaped monster often squeals with laughter, though it too can''t seem to figure out what''s so funny.'),
	('Crawl', 18, 6, 'This monster is absolutely confident in its swimming ability. With its high-tech swimming suit on, it trains every day to become #1 in the world.'),
	('Yuppee', 19, 1, 'Yuppees are usually energetic, jumping, running, and rolling. But when they''re tired and just standing still, they look just like snowmen.'),
	('Octopee', 19, 2, 'Octopee is usually very docile, but once it gets upset, it won''t stop. When you see its eyes change, RUN!'),
	('Octomee', 19, 3, 'An ancient race attempted to give eternal life to this monster. Judging by all those bandages, the experiment must have failed...'),
	('Piyopi', 19, 4, 'This Octopee was born from a hard-shelled egg. It continues to switch shells as it grows, much like a hermit crab.'),
	('Hohocto', 19, 5, 'This Octopee lives in trees. However, they are very bad at climbing, so once they fall out of a tree, they can''t get back up again.'),
	('Dalphi', 19, 6, 'This is a rare black and white Octopee! I''ve heard there are only 102 in the whole world!'),
	('Actopee', 19, 6, 'While monsters have been doing theatre for a long time, Actopee''s performances seem especially popular among women.'),
	('Breeza', 20, 1, 'Said to be shown in conjunction with the aurora. It has been nicknamed the ''Snowfield Queen.'''),
	('Ogyo', 20, 2, 'This magnificent maiden is the most elegant of them all. Because of its great pride, you must be careful how you treat it.'),
	('Munlee', 20, 3, 'This sweet monster performs under the solitude of the desert moon. Dancers often use it in their designs.'),
	('Galberra', 20, 4, 'A happy monster born where varicolored flowers bloom. The scent must have resulted in some sort of monster therapy...'),
	('Odyu', 20, 5, 'This calm character loves to stand in the green grass and breathe deeply. It might not do well in a place too cold or too hot.'),
	('Lovina', 20, 6, 'This blissed-out monster loves bright colors. It is said that anyone who sees it will become happy, but the happiest of all has to be the monster itself.'),
	('Shironcho', 21, 1, 'Don''t speak too loud when you see a Shironcho. It will go inside its shell and never come out.'),
	('Shelluncho', 21, 2, 'It lives in the sea where the currents are calm. It is said that this monster was born from the teardrops of a mermaid. How poetic!'),
	('Tsuboncho', 21, 3, 'Since they say that a Tsuboncho will grant three wishes to the Breeder that has been nice to it, many Breeders tend spoil their Tsubonchos rotten.'),
	('Pancho', 21, 4, 'A huge pumpkin-turned-monster. Like a hermit crab, the shell doesn''t grow, so a new one has to be found periodically. That''s why it makes such a mess.'),
	('Kurincho', 21, 5, 'This monster was found under a huge chestnut tree. Initially, the monster still had burrs and many Breeders were hurt.'),
	('Makyu', 21, 6, 'Makyu mesmerizes its fans with its exciting battles. It is always trying to improve itself, looking for a bigger battlefield.'),
	('Afro', 21, 6, 'There is a planetarium inside. Since the shell kind of looks like a human face, this monster was once thought to bring bad luck.'),
	('Angel', 22, 1, 'Some say it is a messenger from God, which is not true. Some also say it''s good luck if Angel''s eyes are open, but this only happens when it''s angry...'),
	('Windine', 22, 2, 'A Fairy of water, this is where Windine came from. There are rumors it is going out with Jell. Kind of a careless monster.'),
	('Pixie', 22, 3, 'It is very spoiled and mischievous, pretty but not always nice. The male Breeders should be especially careful. Yes, you too.'),
	('Night-Flyer', 22, 4, 'This fairy was meant to be messenger of the night, but now it works in the day. Maybe it is afraid of the dark? Yet it still becomes dizzy with bright light.'),
	('Farn', 22, 5, 'A peaceful and happy fairy that does not get along with the Pixie. It seems something happened between them. I wonder what?'),
	('Nymph', 22, 6, 'A very easy-going fairy that lives in the forest and does not worry about a thing. It loves to sunbathe and sleep in the shade behind a tree.'),
	('Pansy', 22, 6, 'A fairy with a sad past in which it lost everything. It stopped smiling, and its eyes became red from crying for so long.'),
	('Valkyrie', 22, 6, 'This fairy was born to fight. It''s friendly, unless you make it upset. The blue eye can see the future while the red eye can see the past.'),
	('Fantuger', 22, 6, 'A strange fairy that came from the land of Chuka. Some maniacs really love this monster. It is looking for a particular scroll...'),
	('Fay', 22, 6, 'I wonder what misery those dark eyes have seen? It''s said Fay has been through such sadness that the tears have dyed the area around its eyes black...'),
	('Kesshoka', 23, 1, 'When the wind blows, its beautiful song can be heard. The melody makes you sleepy and sometimes you get lost.'),
	('Coconut', 23, 2, 'It moves by drifting in the ocean, so it was thought to be a tiny island. They even called this monster ''Floating Isle.'''),
	('Saboran', 23, 3, 'A famous story describes how a Plant fell in love with a desert Chickchick and had a Lord change it into a Cactaran. If it sees a Chickchick, the flowers turn red.'),
	('Jungle Plum', 23, 4, 'Its dance is so amazing that toys were made to mimic it. I used to have one growing up.'),
	('Plant', 23, 5, 'It was once rumored that if a Plant grew up in Sparta, its flowers would become blue. Although not true, many Plants ran away and became stray monsters.'),
	('Akihabana', 23, 6, 'A mysterious monster who is said to have come from the legendary Electri-city. They say its face sometimes shows this faraway cityscape.'),
	('RabbiRoller', 24, 1, 'One day, a snow rabbit found a roller, sat on it, and found it could not let go. This is how the Rabbiroller was born.'),
	('VivaRoller', 24, 2, 'The sharp fangs are not used to fight, but to clean its rollers. This monster likes to keep things clean and tidy. It lives underwater.'),
	('ArmadiRoller', 24, 3, 'The thorny points come from the skin of Armadiroller. It is always curled up motionless behind the rocks, because it is just too hot.'),
	('Psiroller', 24, 4, 'This monster was recently discovered, and many things are still unknown. Is it just a rhino, or is the roller alive too? It''s still often debated.'),
	('BearRoller', 24, 5, 'One day, a Tochikan girl was taking a walk in the woods when she found this monster. Since the monster kept following her, she decided to keep it.'),
	('BaliRoller', 24, 6, 'Its name is BariRoller. No one can run faster. Its eyes are full of the sadness and happiness of running.'),
	('Tornado', 24, 6, 'This is Tornado. He is the expert of great tackles! No one can approach his dumbbell trained body.'),
	('Raipenpenn', 25, 1, 'It has a rather indistinct face, but this monster can''t. be tricked. Called "The Strongest in the Snowfield," it puts its all into battles.'),
	('Peligoon', 25, 2, 'This cool Pelican is proud of how its beak can hold anything. Will it come to hold your heart, too?'),
	('Griphyon', 25, 3, 'This bird is revered as the King of the Sands, but it is really rather modest. It must be quietly training somewhere in the desert right now...'),
	('Phowou', 25, 4, 'This monster will one day be legendary. It has a strong sense of fairness, and in that red body a heart burns with the flame of justice.'),
	('Raiden', 25, 5, 'This monster never misses daily training. It does not bother with small things, thinking only about ways to become stronger.'),
	('Petraden', 25, 6, 'If you want to know this monster''s history, just ask. It isn''t called a living fossil just for show it really has lived through an eternity.'),
	('Cowbird', 25, 6, 'A Cowbird here from the edge of the wilds. It puts on its prideful hat, and with its quick-draw Western punch aims for the loot.'),
	('Usazo', 26, 1, 'A timid prankster, Suezo likes to hide in the snow and scare people. Once, it even accidentally scared itself!'),
	('Fukazo', 26, 2, 'Fukazo is often mistaken for a shark, and this makes it angry. And when it''s angry, it''s far scarier than a measly shark!'),
	('Suezo', 26, 3, 'Charming and mischievous, this eyeball monster is popular but difficult to handle, hence all the stray Suezos around lately.'),
	('Monzo', 26, 4, 'Monzo loves listening to gossip, but what it doesn''t realize is that its big ears are often the subject of gossip themselves!'),
	('Tanuzo', 26, 5, 'It loves nuts and berries, and can run away quickly. Unlike other Suezos, this one is well-behaved.'),
	('Suecho', 26, 6, 'Due to its upbringing, it is kind of spoiled. If it doesn''t get its way, it throws a fit. Its butler always looks dumbfounded.'),
	('Blizzarin', 27, 1, 'Blizzarin comes in December and gives presents to children, but if you''ve been bad, you may not get any.'),
	('Maririn', 27, 2, 'I heard Maririn used to work for a sea god named Ogyo. They say that Ogyo was a tyrant, and Maririn was always suffering.'),
	('Seniorin', 27, 3, 'If you are ever lost in the desert, try calling for Seniorin! Though it can''t help you, it will make you forget about everything with its funky dance.'),
	('Kuririn', 27, 4, 'When you see Kuririn in the woods, put out your fires. If Kuririn catches fire, it will explode.'),
	('Suzurin', 27, 5, 'Dr. Shiroki found this fairy monster. The doctor found this monster so sweet that he just had to scream ''Woweee!'''),
	('Holstarin', 27, 6, 'People were curious about where this monster gets the milk it brings, so they finally decided to follow it, only to see something they shouldn''t have.'),
	('Drarin', 27, 6, 'A monster from the land of Night. Though it looks dangerous, it actually will faint if it sees blood. It is very popular in the land of Night.'),
	('Kerorin', 27, 6, 'On rainy days Kerorin plays outside then comes inside soaking wet. Some say that Kerorin causes the rain to pour.'),
	('Rayrin', 27, 6, 'A fairy from the land of Chuka. Despite the pale face, it''s very healthy. It loves to take naps, but don''t spoil it too much.'),
	('Tiger', 28, 1, 'Thanks to the Tochikans, the once-feared ''Blue Gale'' can now be trained by anyone. Once you become friends, it will never betray you.'),
	('Galum', 28, 2, 'Galum''s fur repels water, so it never really gets wet. That''s why it can move so swiftly underwater.'),
	('Anubis', 28, 3, 'Anubis lives alone in the desert, and it is very difficult to tame. It takes an experienced breeder to train it. You might be a good match.'),
	('Ryulon', 28, 4, 'The two beautiful horns tell us this is the King of Tigers. Unlike the others, they live in packs and take care of their families.'),
	('Remus', 28, 5, 'This monster was recently discovered in the jungle. Its fur acts as camouflage, which is why no one could find it before.'),
	('Ruby', 28, 6, 'The red body signifies the blood of Nagazi, the strongest monster of all. Maybe there is a Breeder who can revive this monster.'),
	('Fenril', 28, 6, 'It is said this monster once fought with the legendary Dragon, but we don''t know for sure. The scar on its forehead is rumored to be from that battle.'),
	('Dobor I.T.', 28, 6, 'This Tiger once saved a girl from a burning house. Its fur burned away and gave it this new look.'),
	('Zan', 29, 1, 'The only thing this monster knows is how to fight. The Tochikans saw this as a danger and sealed the monster away, but a scientist recently revived it..'),
	('Retsu', 29, 2, 'Impressed by the lifestyle of a crayfish, it tries every day to live like one. This is why it is so good at fighting underwater.'),
	('Bui', 29, 3, 'As a result of living under the strong desert sun, unnecessary body water has evaporated. This is how this monster became lighter and faster than a normal Zan.'),
	('Shin', 29, 4, 'The side of its arms is shaped like a huge blade. It probably uses this to push the tall jungle grass aside as it walks.'),
	('Gai', 29, 5, 'This monster has the fastest airspeed. They say it learned how to fight in midair from a falcon living in the woods.'),
	('Izuna', 29, 6, 'Only a few people have seen Izuna before. It is said this is because Izuna has mastered the martial art of Ninjutsu.'),
	('Pashminer', 30, 1, 'Pashminer is so proud of its gorgeous muffler. It fancies itself to be quite stylish, but no one else really thinks so.'),
	('Palasaulo', 30, 2, 'What looks like a long horn is actually a nose, which allows it to breathe underwater. It is the champion of the swimming contest each year.'),
	('Hotrod', 30, 3, 'This monster runs in the desert at night. It doesn''t really mind that it can only run in straight lines. Its shiny mane is the symbol of a Zoom.'),
	('Gramper', 30, 4, 'It was born with that great looking beard, which can be combined with the horn on its head to see things far, far away.'),
	('Zoom', 30, 5, 'This monster is so gentle and tame that it is often recommended for new breeders. It is also very playful, guaranteed to make you smile.'),
	('Futorunner', 30, 6, 'Its great strides are moving to behold. Some say the name originally came from the fact that it often finds itself running subconsciously.'),
	('Tatoon-J', 30, 6, 'A billionaire spent lots of money to create this battle monster. Its flame tattoo symbolizes its furious fighting style.');

INSERT INTO Region (Region) VALUES 
	('Brillia'),
	('Goat'),
	('Takrama'),
	('Kalaragi'),
	('Morx'),
	('Special');